namespace Shoppa
{
    partial class frmManageProduct
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmManageProduct));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.pbProductImage = new System.Windows.Forms.PictureBox();
            this.btnSelectProductImage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.txtProductName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtQuantityInStock = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cboCategory = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtProductInfo = new System.Windows.Forms.TextBox();
            this.btnDeleteProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAddProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEditProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.cboUnit = new System.Windows.Forms.ComboBox();
            this.label7 = new System.Windows.Forms.Label();
            this.txtProductID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSaveProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbProductImage)).BeginInit();
            this.tableLayoutPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Location = new System.Drawing.Point(11, 248);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.Size = new System.Drawing.Size(869, 367);
            this.dataGridView1.TabIndex = 0;
            this.dataGridView1.RowEnter += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridView1_RowEnter);
            // 
            // pbProductImage
            // 
            this.pbProductImage.BackColor = System.Drawing.Color.MistyRose;
            this.pbProductImage.Image = ((System.Drawing.Image)(resources.GetObject("pbProductImage.Image")));
            this.pbProductImage.Location = new System.Drawing.Point(12, 12);
            this.pbProductImage.Name = "pbProductImage";
            this.pbProductImage.Size = new System.Drawing.Size(130, 130);
            this.pbProductImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbProductImage.TabIndex = 1;
            this.pbProductImage.TabStop = false;
            // 
            // btnSelectProductImage
            // 
            this.btnSelectProductImage.AllowAnimations = true;
            this.btnSelectProductImage.AllowMouseEffects = true;
            this.btnSelectProductImage.AllowToggling = false;
            this.btnSelectProductImage.AnimationSpeed = 200;
            this.btnSelectProductImage.AutoGenerateColors = false;
            this.btnSelectProductImage.AutoRoundBorders = false;
            this.btnSelectProductImage.AutoSizeLeftIcon = true;
            this.btnSelectProductImage.AutoSizeRightIcon = true;
            this.btnSelectProductImage.BackColor = System.Drawing.Color.Transparent;
            this.btnSelectProductImage.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnSelectProductImage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSelectProductImage.BackgroundImage")));
            this.btnSelectProductImage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectProductImage.ButtonText = "Chọn ảnh";
            this.btnSelectProductImage.ButtonTextMarginLeft = 0;
            this.btnSelectProductImage.ColorContrastOnClick = 45;
            this.btnSelectProductImage.ColorContrastOnHover = 45;
            this.btnSelectProductImage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSelectProductImage.CustomizableEdges = borderEdges1;
            this.btnSelectProductImage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSelectProductImage.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSelectProductImage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSelectProductImage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSelectProductImage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSelectProductImage.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnSelectProductImage.ForeColor = System.Drawing.Color.White;
            this.btnSelectProductImage.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnSelectProductImage.IconLeft")));
            this.btnSelectProductImage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSelectProductImage.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSelectProductImage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSelectProductImage.IconMarginLeft = 11;
            this.btnSelectProductImage.IconPadding = 10;
            this.btnSelectProductImage.IconRight = null;
            this.btnSelectProductImage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSelectProductImage.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSelectProductImage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSelectProductImage.IconSize = 25;
            this.btnSelectProductImage.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnSelectProductImage.IdleBorderRadius = 3;
            this.btnSelectProductImage.IdleBorderThickness = 1;
            this.btnSelectProductImage.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnSelectProductImage.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSelectProductImage.IdleIconLeftImage")));
            this.btnSelectProductImage.IdleIconRightImage = null;
            this.btnSelectProductImage.IndicateFocus = false;
            this.btnSelectProductImage.Location = new System.Drawing.Point(12, 152);
            this.btnSelectProductImage.Margin = new System.Windows.Forms.Padding(0);
            this.btnSelectProductImage.Name = "btnSelectProductImage";
            this.btnSelectProductImage.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSelectProductImage.OnDisabledState.BorderRadius = 3;
            this.btnSelectProductImage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectProductImage.OnDisabledState.BorderThickness = 1;
            this.btnSelectProductImage.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSelectProductImage.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSelectProductImage.OnDisabledState.IconLeftImage = null;
            this.btnSelectProductImage.OnDisabledState.IconRightImage = null;
            this.btnSelectProductImage.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnSelectProductImage.onHoverState.BorderRadius = 3;
            this.btnSelectProductImage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectProductImage.onHoverState.BorderThickness = 1;
            this.btnSelectProductImage.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnSelectProductImage.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSelectProductImage.onHoverState.IconLeftImage = null;
            this.btnSelectProductImage.onHoverState.IconRightImage = null;
            this.btnSelectProductImage.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSelectProductImage.OnIdleState.BorderRadius = 3;
            this.btnSelectProductImage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectProductImage.OnIdleState.BorderThickness = 1;
            this.btnSelectProductImage.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSelectProductImage.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSelectProductImage.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSelectProductImage.OnIdleState.IconLeftImage")));
            this.btnSelectProductImage.OnIdleState.IconRightImage = null;
            this.btnSelectProductImage.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSelectProductImage.OnPressedState.BorderRadius = 3;
            this.btnSelectProductImage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelectProductImage.OnPressedState.BorderThickness = 1;
            this.btnSelectProductImage.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSelectProductImage.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSelectProductImage.OnPressedState.IconLeftImage = null;
            this.btnSelectProductImage.OnPressedState.IconRightImage = null;
            this.btnSelectProductImage.Size = new System.Drawing.Size(130, 40);
            this.btnSelectProductImage.TabIndex = 10;
            this.btnSelectProductImage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSelectProductImage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSelectProductImage.TextMarginLeft = 0;
            this.btnSelectProductImage.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnSelectProductImage.UseDefaultRadiusAndThickness = true;
            this.btnSelectProductImage.Click += new System.EventHandler(this.btnSelectProductImage_Click);
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.CellBorderStyle = System.Windows.Forms.TableLayoutPanelCellBorderStyle.Single;
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Controls.Add(this.txtProductID, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.label6, 0, 5);
            this.tableLayoutPanel2.Controls.Add(this.label7, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.label5, 0, 4);
            this.tableLayoutPanel2.Controls.Add(this.label4, 0, 3);
            this.tableLayoutPanel2.Controls.Add(this.label1, 0, 2);
            this.tableLayoutPanel2.Controls.Add(this.label3, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.txtQuantityInStock, 1, 5);
            this.tableLayoutPanel2.Controls.Add(this.txtPrice, 1, 4);
            this.tableLayoutPanel2.Controls.Add(this.cboUnit, 1, 3);
            this.tableLayoutPanel2.Controls.Add(this.cboCategory, 1, 2);
            this.tableLayoutPanel2.Controls.Add(this.txtProductName, 1, 1);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(158, 12);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 6;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(345, 217);
            this.tableLayoutPanel2.TabIndex = 11;
            // 
            // txtProductName
            // 
            this.txtProductName.AcceptsReturn = false;
            this.txtProductName.AcceptsTab = false;
            this.txtProductName.AnimationSpeed = 200;
            this.txtProductName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtProductName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtProductName.AutoSizeHeight = true;
            this.txtProductName.BackColor = System.Drawing.Color.Transparent;
            this.txtProductName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtProductName.BackgroundImage")));
            this.txtProductName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtProductName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtProductName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtProductName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtProductName.BorderRadius = 1;
            this.txtProductName.BorderThickness = 1;
            this.txtProductName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtProductName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtProductName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtProductName.DefaultText = "";
            this.txtProductName.FillColor = System.Drawing.Color.White;
            this.txtProductName.HideSelection = true;
            this.txtProductName.IconLeft = null;
            this.txtProductName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductName.IconPadding = 10;
            this.txtProductName.IconRight = null;
            this.txtProductName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductName.Lines = new string[0];
            this.txtProductName.Location = new System.Drawing.Point(176, 40);
            this.txtProductName.MaxLength = 50;
            this.txtProductName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtProductName.Modified = false;
            this.txtProductName.Multiline = false;
            this.txtProductName.Name = "txtProductName";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProductName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductName.OnIdleState = stateProperties16;
            this.txtProductName.Padding = new System.Windows.Forms.Padding(3);
            this.txtProductName.PasswordChar = '\0';
            this.txtProductName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProductName.PlaceholderText = "iPhone 15 Ultra";
            this.txtProductName.ReadOnly = false;
            this.txtProductName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtProductName.SelectedText = "";
            this.txtProductName.SelectionLength = 0;
            this.txtProductName.SelectionStart = 0;
            this.txtProductName.ShortcutsEnabled = true;
            this.txtProductName.Size = new System.Drawing.Size(165, 29);
            this.txtProductName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtProductName.TabIndex = 0;
            this.txtProductName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtProductName.TextMarginBottom = 0;
            this.txtProductName.TextMarginLeft = 5;
            this.txtProductName.TextMarginTop = 0;
            this.txtProductName.TextPlaceholder = "iPhone 15 Ultra";
            this.txtProductName.UseSystemPasswordChar = false;
            this.txtProductName.WordWrap = true;
            // 
            // txtPrice
            // 
            this.txtPrice.AcceptsReturn = false;
            this.txtPrice.AcceptsTab = false;
            this.txtPrice.AnimationSpeed = 200;
            this.txtPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrice.AutoSizeHeight = true;
            this.txtPrice.BackColor = System.Drawing.Color.Transparent;
            this.txtPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrice.BackgroundImage")));
            this.txtPrice.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPrice.BorderRadius = 1;
            this.txtPrice.BorderThickness = 1;
            this.txtPrice.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrice.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtPrice.DefaultText = "";
            this.txtPrice.FillColor = System.Drawing.Color.White;
            this.txtPrice.HideSelection = true;
            this.txtPrice.IconLeft = null;
            this.txtPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrice.IconPadding = 10;
            this.txtPrice.IconRight = null;
            this.txtPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrice.Lines = new string[0];
            this.txtPrice.Location = new System.Drawing.Point(176, 148);
            this.txtPrice.MaxLength = 100;
            this.txtPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrice.Modified = false;
            this.txtPrice.Multiline = false;
            this.txtPrice.Name = "txtPrice";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrice.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPrice.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrice.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrice.OnIdleState = stateProperties12;
            this.txtPrice.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrice.PasswordChar = '\0';
            this.txtPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPrice.PlaceholderText = "10.000";
            this.txtPrice.ReadOnly = false;
            this.txtPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrice.SelectedText = "";
            this.txtPrice.SelectionLength = 0;
            this.txtPrice.SelectionStart = 0;
            this.txtPrice.ShortcutsEnabled = true;
            this.txtPrice.Size = new System.Drawing.Size(165, 29);
            this.txtPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrice.TabIndex = 2;
            this.txtPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrice.TextMarginBottom = 0;
            this.txtPrice.TextMarginLeft = 5;
            this.txtPrice.TextMarginTop = 0;
            this.txtPrice.TextPlaceholder = "10.000";
            this.txtPrice.UseSystemPasswordChar = false;
            this.txtPrice.WordWrap = true;
            // 
            // txtQuantityInStock
            // 
            this.txtQuantityInStock.AcceptsReturn = false;
            this.txtQuantityInStock.AcceptsTab = false;
            this.txtQuantityInStock.AnimationSpeed = 200;
            this.txtQuantityInStock.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtQuantityInStock.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtQuantityInStock.AutoSizeHeight = true;
            this.txtQuantityInStock.BackColor = System.Drawing.Color.Transparent;
            this.txtQuantityInStock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtQuantityInStock.BackgroundImage")));
            this.txtQuantityInStock.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtQuantityInStock.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtQuantityInStock.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtQuantityInStock.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtQuantityInStock.BorderRadius = 1;
            this.txtQuantityInStock.BorderThickness = 1;
            this.txtQuantityInStock.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtQuantityInStock.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtQuantityInStock.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantityInStock.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtQuantityInStock.DefaultText = "";
            this.txtQuantityInStock.FillColor = System.Drawing.Color.White;
            this.txtQuantityInStock.HideSelection = true;
            this.txtQuantityInStock.IconLeft = null;
            this.txtQuantityInStock.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantityInStock.IconPadding = 10;
            this.txtQuantityInStock.IconRight = null;
            this.txtQuantityInStock.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtQuantityInStock.Lines = new string[0];
            this.txtQuantityInStock.Location = new System.Drawing.Point(176, 184);
            this.txtQuantityInStock.MaxLength = 10;
            this.txtQuantityInStock.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtQuantityInStock.Modified = false;
            this.txtQuantityInStock.Multiline = false;
            this.txtQuantityInStock.Name = "txtQuantityInStock";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantityInStock.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtQuantityInStock.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantityInStock.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtQuantityInStock.OnIdleState = stateProperties8;
            this.txtQuantityInStock.Padding = new System.Windows.Forms.Padding(3);
            this.txtQuantityInStock.PasswordChar = '\0';
            this.txtQuantityInStock.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtQuantityInStock.PlaceholderText = "3";
            this.txtQuantityInStock.ReadOnly = false;
            this.txtQuantityInStock.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtQuantityInStock.SelectedText = "";
            this.txtQuantityInStock.SelectionLength = 0;
            this.txtQuantityInStock.SelectionStart = 0;
            this.txtQuantityInStock.ShortcutsEnabled = true;
            this.txtQuantityInStock.Size = new System.Drawing.Size(165, 29);
            this.txtQuantityInStock.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtQuantityInStock.TabIndex = 1;
            this.txtQuantityInStock.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtQuantityInStock.TextMarginBottom = 0;
            this.txtQuantityInStock.TextMarginLeft = 5;
            this.txtQuantityInStock.TextMarginTop = 0;
            this.txtQuantityInStock.TextPlaceholder = "3";
            this.txtQuantityInStock.UseSystemPasswordChar = false;
            this.txtQuantityInStock.WordWrap = true;
            // 
            // cboCategory
            // 
            this.cboCategory.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategory.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cboCategory.FormattingEnabled = true;
            this.cboCategory.Location = new System.Drawing.Point(176, 76);
            this.cboCategory.Name = "cboCategory";
            this.cboCategory.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.cboCategory.Size = new System.Drawing.Size(163, 25);
            this.cboCategory.TabIndex = 3;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(526, 15);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(89, 13);
            this.label2.TabIndex = 19;
            this.label2.Text = "Mô tả sản phẩm";
            // 
            // txtProductInfo
            // 
            this.txtProductInfo.Location = new System.Drawing.Point(524, 35);
            this.txtProductInfo.MaxLength = 200;
            this.txtProductInfo.Multiline = true;
            this.txtProductInfo.Name = "txtProductInfo";
            this.txtProductInfo.Size = new System.Drawing.Size(357, 114);
            this.txtProductInfo.TabIndex = 18;
            this.txtProductInfo.Text = "- ABC\r\n- Sản phẩm này bla, bla\r\n";
            // 
            // btnDeleteProduct
            // 
            this.btnDeleteProduct.AllowAnimations = true;
            this.btnDeleteProduct.AllowMouseEffects = true;
            this.btnDeleteProduct.AllowToggling = false;
            this.btnDeleteProduct.AnimationSpeed = 200;
            this.btnDeleteProduct.AutoGenerateColors = false;
            this.btnDeleteProduct.AutoRoundBorders = false;
            this.btnDeleteProduct.AutoSizeLeftIcon = true;
            this.btnDeleteProduct.AutoSizeRightIcon = true;
            this.btnDeleteProduct.BackColor = System.Drawing.Color.Transparent;
            this.btnDeleteProduct.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDeleteProduct.BackgroundImage")));
            this.btnDeleteProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.ButtonText = "Xóa";
            this.btnDeleteProduct.ButtonTextMarginLeft = 0;
            this.btnDeleteProduct.ColorContrastOnClick = 45;
            this.btnDeleteProduct.ColorContrastOnHover = 45;
            this.btnDeleteProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnDeleteProduct.CustomizableEdges = borderEdges2;
            this.btnDeleteProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDeleteProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeleteProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeleteProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeleteProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDeleteProduct.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnDeleteProduct.ForeColor = System.Drawing.Color.White;
            this.btnDeleteProduct.IconLeft = null;
            this.btnDeleteProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDeleteProduct.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDeleteProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDeleteProduct.IconMarginLeft = 11;
            this.btnDeleteProduct.IconPadding = 10;
            this.btnDeleteProduct.IconRight = null;
            this.btnDeleteProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDeleteProduct.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDeleteProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDeleteProduct.IconSize = 25;
            this.btnDeleteProduct.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.IdleBorderRadius = 3;
            this.btnDeleteProduct.IdleBorderThickness = 1;
            this.btnDeleteProduct.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.IdleIconLeftImage = null;
            this.btnDeleteProduct.IdleIconRightImage = null;
            this.btnDeleteProduct.IndicateFocus = false;
            this.btnDeleteProduct.Location = new System.Drawing.Point(770, 164);
            this.btnDeleteProduct.Margin = new System.Windows.Forms.Padding(0);
            this.btnDeleteProduct.Name = "btnDeleteProduct";
            this.btnDeleteProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeleteProduct.OnDisabledState.BorderRadius = 3;
            this.btnDeleteProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.OnDisabledState.BorderThickness = 1;
            this.btnDeleteProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeleteProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeleteProduct.OnDisabledState.IconLeftImage = null;
            this.btnDeleteProduct.OnDisabledState.IconRightImage = null;
            this.btnDeleteProduct.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnDeleteProduct.onHoverState.BorderRadius = 3;
            this.btnDeleteProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.onHoverState.BorderThickness = 1;
            this.btnDeleteProduct.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnDeleteProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteProduct.onHoverState.IconLeftImage = null;
            this.btnDeleteProduct.onHoverState.IconRightImage = null;
            this.btnDeleteProduct.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.OnIdleState.BorderRadius = 3;
            this.btnDeleteProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.OnIdleState.BorderThickness = 1;
            this.btnDeleteProduct.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteProduct.OnIdleState.IconLeftImage = null;
            this.btnDeleteProduct.OnIdleState.IconRightImage = null;
            this.btnDeleteProduct.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.OnPressedState.BorderRadius = 3;
            this.btnDeleteProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.OnPressedState.BorderThickness = 1;
            this.btnDeleteProduct.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteProduct.OnPressedState.IconLeftImage = null;
            this.btnDeleteProduct.OnPressedState.IconRightImage = null;
            this.btnDeleteProduct.Size = new System.Drawing.Size(110, 28);
            this.btnDeleteProduct.TabIndex = 20;
            this.btnDeleteProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDeleteProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDeleteProduct.TextMarginLeft = 0;
            this.btnDeleteProduct.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnDeleteProduct.UseDefaultRadiusAndThickness = true;
            this.btnDeleteProduct.Click += new System.EventHandler(this.btnDeleteProduct_Click);
            // 
            // btnAddProduct
            // 
            this.btnAddProduct.AllowAnimations = true;
            this.btnAddProduct.AllowMouseEffects = true;
            this.btnAddProduct.AllowToggling = false;
            this.btnAddProduct.AnimationSpeed = 200;
            this.btnAddProduct.AutoGenerateColors = false;
            this.btnAddProduct.AutoRoundBorders = false;
            this.btnAddProduct.AutoSizeLeftIcon = true;
            this.btnAddProduct.AutoSizeRightIcon = true;
            this.btnAddProduct.BackColor = System.Drawing.Color.Transparent;
            this.btnAddProduct.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnAddProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddProduct.BackgroundImage")));
            this.btnAddProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddProduct.ButtonText = "Thêm";
            this.btnAddProduct.ButtonTextMarginLeft = 0;
            this.btnAddProduct.ColorContrastOnClick = 45;
            this.btnAddProduct.ColorContrastOnHover = 45;
            this.btnAddProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAddProduct.CustomizableEdges = borderEdges3;
            this.btnAddProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAddProduct.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnAddProduct.ForeColor = System.Drawing.Color.White;
            this.btnAddProduct.IconLeft = null;
            this.btnAddProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddProduct.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAddProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddProduct.IconMarginLeft = 11;
            this.btnAddProduct.IconPadding = 10;
            this.btnAddProduct.IconRight = null;
            this.btnAddProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddProduct.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAddProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddProduct.IconSize = 25;
            this.btnAddProduct.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnAddProduct.IdleBorderRadius = 3;
            this.btnAddProduct.IdleBorderThickness = 1;
            this.btnAddProduct.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnAddProduct.IdleIconLeftImage = null;
            this.btnAddProduct.IdleIconRightImage = null;
            this.btnAddProduct.IndicateFocus = false;
            this.btnAddProduct.Location = new System.Drawing.Point(524, 164);
            this.btnAddProduct.Margin = new System.Windows.Forms.Padding(0);
            this.btnAddProduct.Name = "btnAddProduct";
            this.btnAddProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddProduct.OnDisabledState.BorderRadius = 3;
            this.btnAddProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddProduct.OnDisabledState.BorderThickness = 1;
            this.btnAddProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddProduct.OnDisabledState.IconLeftImage = null;
            this.btnAddProduct.OnDisabledState.IconRightImage = null;
            this.btnAddProduct.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnAddProduct.onHoverState.BorderRadius = 3;
            this.btnAddProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddProduct.onHoverState.BorderThickness = 1;
            this.btnAddProduct.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnAddProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAddProduct.onHoverState.IconLeftImage = null;
            this.btnAddProduct.onHoverState.IconRightImage = null;
            this.btnAddProduct.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnAddProduct.OnIdleState.BorderRadius = 3;
            this.btnAddProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddProduct.OnIdleState.BorderThickness = 1;
            this.btnAddProduct.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnAddProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddProduct.OnIdleState.IconLeftImage = null;
            this.btnAddProduct.OnIdleState.IconRightImage = null;
            this.btnAddProduct.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnAddProduct.OnPressedState.BorderRadius = 3;
            this.btnAddProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddProduct.OnPressedState.BorderThickness = 1;
            this.btnAddProduct.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnAddProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAddProduct.OnPressedState.IconLeftImage = null;
            this.btnAddProduct.OnPressedState.IconRightImage = null;
            this.btnAddProduct.Size = new System.Drawing.Size(110, 28);
            this.btnAddProduct.TabIndex = 21;
            this.btnAddProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddProduct.TextMarginLeft = 0;
            this.btnAddProduct.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnAddProduct.UseDefaultRadiusAndThickness = true;
            this.btnAddProduct.Click += new System.EventHandler(this.btnAddProduct_Click);
            // 
            // btnEditProduct
            // 
            this.btnEditProduct.AllowAnimations = true;
            this.btnEditProduct.AllowMouseEffects = true;
            this.btnEditProduct.AllowToggling = false;
            this.btnEditProduct.AnimationSpeed = 200;
            this.btnEditProduct.AutoGenerateColors = false;
            this.btnEditProduct.AutoRoundBorders = false;
            this.btnEditProduct.AutoSizeLeftIcon = true;
            this.btnEditProduct.AutoSizeRightIcon = true;
            this.btnEditProduct.BackColor = System.Drawing.Color.Transparent;
            this.btnEditProduct.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditProduct.BackgroundImage")));
            this.btnEditProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.ButtonText = "Sửa";
            this.btnEditProduct.ButtonTextMarginLeft = 0;
            this.btnEditProduct.ColorContrastOnClick = 45;
            this.btnEditProduct.ColorContrastOnHover = 45;
            this.btnEditProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnEditProduct.CustomizableEdges = borderEdges4;
            this.btnEditProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEditProduct.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnEditProduct.ForeColor = System.Drawing.Color.White;
            this.btnEditProduct.IconLeft = null;
            this.btnEditProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditProduct.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnEditProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEditProduct.IconMarginLeft = 11;
            this.btnEditProduct.IconPadding = 10;
            this.btnEditProduct.IconRight = null;
            this.btnEditProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditProduct.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnEditProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEditProduct.IconSize = 25;
            this.btnEditProduct.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.IdleBorderRadius = 3;
            this.btnEditProduct.IdleBorderThickness = 1;
            this.btnEditProduct.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.IdleIconLeftImage = null;
            this.btnEditProduct.IdleIconRightImage = null;
            this.btnEditProduct.IndicateFocus = false;
            this.btnEditProduct.Location = new System.Drawing.Point(647, 164);
            this.btnEditProduct.Margin = new System.Windows.Forms.Padding(0);
            this.btnEditProduct.Name = "btnEditProduct";
            this.btnEditProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditProduct.OnDisabledState.BorderRadius = 3;
            this.btnEditProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.OnDisabledState.BorderThickness = 1;
            this.btnEditProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditProduct.OnDisabledState.IconLeftImage = null;
            this.btnEditProduct.OnDisabledState.IconRightImage = null;
            this.btnEditProduct.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnEditProduct.onHoverState.BorderRadius = 3;
            this.btnEditProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.onHoverState.BorderThickness = 1;
            this.btnEditProduct.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnEditProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEditProduct.onHoverState.IconLeftImage = null;
            this.btnEditProduct.onHoverState.IconRightImage = null;
            this.btnEditProduct.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.OnIdleState.BorderRadius = 3;
            this.btnEditProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.OnIdleState.BorderThickness = 1;
            this.btnEditProduct.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEditProduct.OnIdleState.IconLeftImage = null;
            this.btnEditProduct.OnIdleState.IconRightImage = null;
            this.btnEditProduct.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.OnPressedState.BorderRadius = 3;
            this.btnEditProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.OnPressedState.BorderThickness = 1;
            this.btnEditProduct.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEditProduct.OnPressedState.IconLeftImage = null;
            this.btnEditProduct.OnPressedState.IconRightImage = null;
            this.btnEditProduct.Size = new System.Drawing.Size(110, 28);
            this.btnEditProduct.TabIndex = 22;
            this.btnEditProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditProduct.TextMarginLeft = 0;
            this.btnEditProduct.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnEditProduct.UseDefaultRadiusAndThickness = true;
            this.btnEditProduct.Click += new System.EventHandler(this.btnEditProduct_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(6, 42);
            this.label3.Margin = new System.Windows.Forms.Padding(5);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(96, 17);
            this.label3.TabIndex = 20;
            this.label3.Text = "Tên sản phẩm:";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(6, 78);
            this.label1.Margin = new System.Windows.Forms.Padding(5);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(98, 17);
            this.label1.TabIndex = 21;
            this.label1.Text = "Loại mặt hàng:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(6, 114);
            this.label4.Margin = new System.Windows.Forms.Padding(5);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(50, 17);
            this.label4.TabIndex = 22;
            this.label4.Text = "Đơn vị:";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(6, 150);
            this.label5.Margin = new System.Windows.Forms.Padding(5);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(69, 17);
            this.label5.TabIndex = 23;
            this.label5.Text = "Giá (VND):";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(6, 186);
            this.label6.Margin = new System.Windows.Forms.Padding(5);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(130, 17);
            this.label6.TabIndex = 24;
            this.label6.Text = "Số lượng trong kho:";
            // 
            // cboUnit
            // 
            this.cboUnit.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboUnit.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cboUnit.FormattingEnabled = true;
            this.cboUnit.Location = new System.Drawing.Point(176, 112);
            this.cboUnit.Name = "cboUnit";
            this.cboUnit.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.cboUnit.Size = new System.Drawing.Size(163, 25);
            this.cboUnit.TabIndex = 23;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(6, 6);
            this.label7.Margin = new System.Windows.Forms.Padding(5);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(94, 17);
            this.label7.TabIndex = 23;
            this.label7.Text = "Mã sản phẩm:";
            // 
            // txtProductID
            // 
            this.txtProductID.AcceptsReturn = false;
            this.txtProductID.AcceptsTab = false;
            this.txtProductID.AnimationSpeed = 200;
            this.txtProductID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtProductID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtProductID.AutoSizeHeight = true;
            this.txtProductID.BackColor = System.Drawing.Color.Transparent;
            this.txtProductID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtProductID.BackgroundImage")));
            this.txtProductID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtProductID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtProductID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtProductID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtProductID.BorderRadius = 1;
            this.txtProductID.BorderThickness = 1;
            this.txtProductID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtProductID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtProductID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductID.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtProductID.DefaultText = "";
            this.txtProductID.FillColor = System.Drawing.Color.White;
            this.txtProductID.HideSelection = true;
            this.txtProductID.IconLeft = null;
            this.txtProductID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductID.IconPadding = 10;
            this.txtProductID.IconRight = null;
            this.txtProductID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductID.Lines = new string[0];
            this.txtProductID.Location = new System.Drawing.Point(176, 4);
            this.txtProductID.MaxLength = 10;
            this.txtProductID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtProductID.Modified = false;
            this.txtProductID.Multiline = false;
            this.txtProductID.Name = "txtProductID";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProductID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductID.OnIdleState = stateProperties4;
            this.txtProductID.Padding = new System.Windows.Forms.Padding(3);
            this.txtProductID.PasswordChar = '\0';
            this.txtProductID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProductID.PlaceholderText = "";
            this.txtProductID.ReadOnly = false;
            this.txtProductID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtProductID.SelectedText = "";
            this.txtProductID.SelectionLength = 0;
            this.txtProductID.SelectionStart = 0;
            this.txtProductID.ShortcutsEnabled = true;
            this.txtProductID.Size = new System.Drawing.Size(165, 29);
            this.txtProductID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtProductID.TabIndex = 24;
            this.txtProductID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtProductID.TextMarginBottom = 0;
            this.txtProductID.TextMarginLeft = 5;
            this.txtProductID.TextMarginTop = 0;
            this.txtProductID.TextPlaceholder = "";
            this.txtProductID.UseSystemPasswordChar = false;
            this.txtProductID.WordWrap = true;
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Hủy bỏ";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges5;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeft = null;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRight = null;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.IdleBorderRadius = 3;
            this.btnCancel.IdleBorderThickness = 1;
            this.btnCancel.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(647, 201);
            this.btnCancel.Margin = new System.Windows.Forms.Padding(0);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 3;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnCancel.onHoverState.BorderRadius = 3;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnIdleState.BorderRadius = 3;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnPressedState.BorderRadius = 3;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(110, 28);
            this.btnCancel.TabIndex = 25;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnSaveProduct
            // 
            this.btnSaveProduct.AllowAnimations = true;
            this.btnSaveProduct.AllowMouseEffects = true;
            this.btnSaveProduct.AllowToggling = false;
            this.btnSaveProduct.AnimationSpeed = 200;
            this.btnSaveProduct.AutoGenerateColors = false;
            this.btnSaveProduct.AutoRoundBorders = false;
            this.btnSaveProduct.AutoSizeLeftIcon = true;
            this.btnSaveProduct.AutoSizeRightIcon = true;
            this.btnSaveProduct.BackColor = System.Drawing.Color.Transparent;
            this.btnSaveProduct.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnSaveProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSaveProduct.BackgroundImage")));
            this.btnSaveProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveProduct.ButtonText = "Ghi";
            this.btnSaveProduct.ButtonTextMarginLeft = 0;
            this.btnSaveProduct.ColorContrastOnClick = 45;
            this.btnSaveProduct.ColorContrastOnHover = 45;
            this.btnSaveProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnSaveProduct.CustomizableEdges = borderEdges6;
            this.btnSaveProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSaveProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSaveProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSaveProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSaveProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSaveProduct.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnSaveProduct.ForeColor = System.Drawing.Color.White;
            this.btnSaveProduct.IconLeft = null;
            this.btnSaveProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSaveProduct.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSaveProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSaveProduct.IconMarginLeft = 11;
            this.btnSaveProduct.IconPadding = 10;
            this.btnSaveProduct.IconRight = null;
            this.btnSaveProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSaveProduct.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSaveProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSaveProduct.IconSize = 25;
            this.btnSaveProduct.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnSaveProduct.IdleBorderRadius = 3;
            this.btnSaveProduct.IdleBorderThickness = 1;
            this.btnSaveProduct.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnSaveProduct.IdleIconLeftImage = null;
            this.btnSaveProduct.IdleIconRightImage = null;
            this.btnSaveProduct.IndicateFocus = false;
            this.btnSaveProduct.Location = new System.Drawing.Point(524, 201);
            this.btnSaveProduct.Margin = new System.Windows.Forms.Padding(0);
            this.btnSaveProduct.Name = "btnSaveProduct";
            this.btnSaveProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSaveProduct.OnDisabledState.BorderRadius = 3;
            this.btnSaveProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveProduct.OnDisabledState.BorderThickness = 1;
            this.btnSaveProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSaveProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSaveProduct.OnDisabledState.IconLeftImage = null;
            this.btnSaveProduct.OnDisabledState.IconRightImage = null;
            this.btnSaveProduct.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnSaveProduct.onHoverState.BorderRadius = 3;
            this.btnSaveProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveProduct.onHoverState.BorderThickness = 1;
            this.btnSaveProduct.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnSaveProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSaveProduct.onHoverState.IconLeftImage = null;
            this.btnSaveProduct.onHoverState.IconRightImage = null;
            this.btnSaveProduct.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSaveProduct.OnIdleState.BorderRadius = 3;
            this.btnSaveProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveProduct.OnIdleState.BorderThickness = 1;
            this.btnSaveProduct.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSaveProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSaveProduct.OnIdleState.IconLeftImage = null;
            this.btnSaveProduct.OnIdleState.IconRightImage = null;
            this.btnSaveProduct.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSaveProduct.OnPressedState.BorderRadius = 3;
            this.btnSaveProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveProduct.OnPressedState.BorderThickness = 1;
            this.btnSaveProduct.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSaveProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSaveProduct.OnPressedState.IconLeftImage = null;
            this.btnSaveProduct.OnPressedState.IconRightImage = null;
            this.btnSaveProduct.Size = new System.Drawing.Size(110, 28);
            this.btnSaveProduct.TabIndex = 24;
            this.btnSaveProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSaveProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSaveProduct.TextMarginLeft = 0;
            this.btnSaveProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSaveProduct.UseDefaultRadiusAndThickness = true;
            this.btnSaveProduct.Click += new System.EventHandler(this.btnSaveProduct_Click);
            // 
            // btnClose
            // 
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowMouseEffects = true;
            this.btnClose.AllowToggling = false;
            this.btnClose.AnimationSpeed = 200;
            this.btnClose.AutoGenerateColors = false;
            this.btnClose.AutoRoundBorders = false;
            this.btnClose.AutoSizeLeftIcon = true;
            this.btnClose.AutoSizeRightIcon = true;
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose.BackgroundImage")));
            this.btnClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.ButtonText = "Thoát";
            this.btnClose.ButtonTextMarginLeft = 0;
            this.btnClose.ColorContrastOnClick = 45;
            this.btnClose.ColorContrastOnHover = 45;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnClose.CustomizableEdges = borderEdges7;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnClose.ForeColor = System.Drawing.Color.White;
            this.btnClose.IconLeft = null;
            this.btnClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose.IconMarginLeft = 11;
            this.btnClose.IconPadding = 10;
            this.btnClose.IconRight = null;
            this.btnClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose.IconSize = 25;
            this.btnClose.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnClose.IdleBorderRadius = 3;
            this.btnClose.IdleBorderThickness = 1;
            this.btnClose.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnClose.IdleIconLeftImage = null;
            this.btnClose.IdleIconRightImage = null;
            this.btnClose.IndicateFocus = false;
            this.btnClose.Location = new System.Drawing.Point(770, 201);
            this.btnClose.Margin = new System.Windows.Forms.Padding(0);
            this.btnClose.Name = "btnClose";
            this.btnClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.OnDisabledState.BorderRadius = 3;
            this.btnClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnDisabledState.BorderThickness = 1;
            this.btnClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.OnDisabledState.IconLeftImage = null;
            this.btnClose.OnDisabledState.IconRightImage = null;
            this.btnClose.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnClose.onHoverState.BorderRadius = 3;
            this.btnClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.onHoverState.BorderThickness = 1;
            this.btnClose.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClose.onHoverState.IconLeftImage = null;
            this.btnClose.onHoverState.IconRightImage = null;
            this.btnClose.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnIdleState.BorderRadius = 3;
            this.btnClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnIdleState.BorderThickness = 1;
            this.btnClose.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnIdleState.IconLeftImage = null;
            this.btnClose.OnIdleState.IconRightImage = null;
            this.btnClose.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnPressedState.BorderRadius = 3;
            this.btnClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnPressedState.BorderThickness = 1;
            this.btnClose.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnPressedState.IconLeftImage = null;
            this.btnClose.OnPressedState.IconRightImage = null;
            this.btnClose.Size = new System.Drawing.Size(110, 28);
            this.btnClose.TabIndex = 23;
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose.TextMarginLeft = 0;
            this.btnClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose.UseDefaultRadiusAndThickness = true;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // frmManageProduct
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(893, 627);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnSaveProduct);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.btnEditProduct);
            this.Controls.Add(this.btnAddProduct);
            this.Controls.Add(this.btnDeleteProduct);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.txtProductInfo);
            this.Controls.Add(this.tableLayoutPanel2);
            this.Controls.Add(this.btnSelectProductImage);
            this.Controls.Add(this.pbProductImage);
            this.Controls.Add(this.dataGridView1);
            this.Font = new System.Drawing.Font("Segoe UI Semibold", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "frmManageProduct";
            this.Text = "Quản lý mặt hàng";
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbProductImage)).EndInit();
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.DataGridView dataGridView1;
        private System.Windows.Forms.PictureBox pbProductImage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSelectProductImage;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtProductName;
        private Bunifu.UI.WinForms.BunifuTextBox txtPrice;
        private Bunifu.UI.WinForms.BunifuTextBox txtQuantityInStock;
        private System.Windows.Forms.ComboBox cboCategory;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtProductInfo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDeleteProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEditProduct;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.ComboBox cboUnit;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox txtProductID;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSaveProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClose;
    }
}