namespace Shoppa
{
    partial class frmManageCategory
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmManageCategory));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.label8 = new System.Windows.Forms.Label();
            this.btnSaveCategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEditCategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtCategoryID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDeleteCategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtCategoryName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnAddCategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.label4 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.txtProductCount = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTotalQuantityInStock = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.label1 = new System.Windows.Forms.Label();
            this.flowLayoutPanel3 = new System.Windows.Forms.FlowLayoutPanel();
            this.txtSearchBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnSearch = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tableLayoutPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.flowLayoutPanel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(420, 131);
            this.label8.Margin = new System.Windows.Forms.Padding(5);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(66, 17);
            this.label8.TabIndex = 46;
            this.label8.Text = "Tìm kiếm:";
            // 
            // btnSaveCategory
            // 
            this.btnSaveCategory.AllowAnimations = true;
            this.btnSaveCategory.AllowMouseEffects = true;
            this.btnSaveCategory.AllowToggling = false;
            this.btnSaveCategory.AnimationSpeed = 200;
            this.btnSaveCategory.AutoGenerateColors = false;
            this.btnSaveCategory.AutoRoundBorders = false;
            this.btnSaveCategory.AutoSizeLeftIcon = true;
            this.btnSaveCategory.AutoSizeRightIcon = true;
            this.btnSaveCategory.BackColor = System.Drawing.Color.Transparent;
            this.btnSaveCategory.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnSaveCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSaveCategory.BackgroundImage")));
            this.btnSaveCategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveCategory.ButtonText = "Ghi";
            this.btnSaveCategory.ButtonTextMarginLeft = 0;
            this.btnSaveCategory.ColorContrastOnClick = 45;
            this.btnSaveCategory.ColorContrastOnHover = 45;
            this.btnSaveCategory.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSaveCategory.CustomizableEdges = borderEdges1;
            this.btnSaveCategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSaveCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSaveCategory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSaveCategory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSaveCategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSaveCategory.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnSaveCategory.ForeColor = System.Drawing.Color.White;
            this.btnSaveCategory.IconLeft = null;
            this.btnSaveCategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSaveCategory.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSaveCategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSaveCategory.IconMarginLeft = 11;
            this.btnSaveCategory.IconPadding = 10;
            this.btnSaveCategory.IconRight = null;
            this.btnSaveCategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSaveCategory.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSaveCategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSaveCategory.IconSize = 25;
            this.btnSaveCategory.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnSaveCategory.IdleBorderRadius = 3;
            this.btnSaveCategory.IdleBorderThickness = 1;
            this.btnSaveCategory.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnSaveCategory.IdleIconLeftImage = null;
            this.btnSaveCategory.IdleIconRightImage = null;
            this.btnSaveCategory.IndicateFocus = false;
            this.btnSaveCategory.Location = new System.Drawing.Point(423, 77);
            this.btnSaveCategory.Margin = new System.Windows.Forms.Padding(0);
            this.btnSaveCategory.Name = "btnSaveCategory";
            this.btnSaveCategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSaveCategory.OnDisabledState.BorderRadius = 3;
            this.btnSaveCategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveCategory.OnDisabledState.BorderThickness = 1;
            this.btnSaveCategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSaveCategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSaveCategory.OnDisabledState.IconLeftImage = null;
            this.btnSaveCategory.OnDisabledState.IconRightImage = null;
            this.btnSaveCategory.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnSaveCategory.onHoverState.BorderRadius = 3;
            this.btnSaveCategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveCategory.onHoverState.BorderThickness = 1;
            this.btnSaveCategory.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnSaveCategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSaveCategory.onHoverState.IconLeftImage = null;
            this.btnSaveCategory.onHoverState.IconRightImage = null;
            this.btnSaveCategory.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSaveCategory.OnIdleState.BorderRadius = 3;
            this.btnSaveCategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveCategory.OnIdleState.BorderThickness = 1;
            this.btnSaveCategory.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSaveCategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSaveCategory.OnIdleState.IconLeftImage = null;
            this.btnSaveCategory.OnIdleState.IconRightImage = null;
            this.btnSaveCategory.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSaveCategory.OnPressedState.BorderRadius = 3;
            this.btnSaveCategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSaveCategory.OnPressedState.BorderThickness = 1;
            this.btnSaveCategory.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSaveCategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSaveCategory.OnPressedState.IconLeftImage = null;
            this.btnSaveCategory.OnPressedState.IconRightImage = null;
            this.btnSaveCategory.Size = new System.Drawing.Size(110, 28);
            this.btnSaveCategory.TabIndex = 44;
            this.btnSaveCategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSaveCategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSaveCategory.TextMarginLeft = 0;
            this.btnSaveCategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSaveCategory.UseDefaultRadiusAndThickness = true;
            this.btnSaveCategory.Click += new System.EventHandler(this.btnSaveCategory_Click);
            // 
            // btnClose
            // 
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowMouseEffects = true;
            this.btnClose.AllowToggling = false;
            this.btnClose.AnimationSpeed = 200;
            this.btnClose.AutoGenerateColors = false;
            this.btnClose.AutoRoundBorders = false;
            this.btnClose.AutoSizeLeftIcon = true;
            this.btnClose.AutoSizeRightIcon = true;
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose.BackgroundImage")));
            this.btnClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.ButtonText = "Thoát";
            this.btnClose.ButtonTextMarginLeft = 0;
            this.btnClose.ColorContrastOnClick = 45;
            this.btnClose.ColorContrastOnHover = 45;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnClose.CustomizableEdges = borderEdges2;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnClose.ForeColor = System.Drawing.Color.White;
            this.btnClose.IconLeft = null;
            this.btnClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose.IconMarginLeft = 11;
            this.btnClose.IconPadding = 10;
            this.btnClose.IconRight = null;
            this.btnClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose.IconSize = 25;
            this.btnClose.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnClose.IdleBorderRadius = 3;
            this.btnClose.IdleBorderThickness = 1;
            this.btnClose.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnClose.IdleIconLeftImage = null;
            this.btnClose.IdleIconRightImage = null;
            this.btnClose.IndicateFocus = false;
            this.btnClose.Location = new System.Drawing.Point(669, 77);
            this.btnClose.Margin = new System.Windows.Forms.Padding(0);
            this.btnClose.Name = "btnClose";
            this.btnClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.OnDisabledState.BorderRadius = 3;
            this.btnClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnDisabledState.BorderThickness = 1;
            this.btnClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.OnDisabledState.IconLeftImage = null;
            this.btnClose.OnDisabledState.IconRightImage = null;
            this.btnClose.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnClose.onHoverState.BorderRadius = 3;
            this.btnClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.onHoverState.BorderThickness = 1;
            this.btnClose.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClose.onHoverState.IconLeftImage = null;
            this.btnClose.onHoverState.IconRightImage = null;
            this.btnClose.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnIdleState.BorderRadius = 3;
            this.btnClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnIdleState.BorderThickness = 1;
            this.btnClose.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnIdleState.IconLeftImage = null;
            this.btnClose.OnIdleState.IconRightImage = null;
            this.btnClose.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnPressedState.BorderRadius = 3;
            this.btnClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnPressedState.BorderThickness = 1;
            this.btnClose.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnPressedState.IconLeftImage = null;
            this.btnClose.OnPressedState.IconRightImage = null;
            this.btnClose.Size = new System.Drawing.Size(110, 28);
            this.btnClose.TabIndex = 43;
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose.TextMarginLeft = 0;
            this.btnClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose.UseDefaultRadiusAndThickness = true;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // btnEditCategory
            // 
            this.btnEditCategory.AllowAnimations = true;
            this.btnEditCategory.AllowMouseEffects = true;
            this.btnEditCategory.AllowToggling = false;
            this.btnEditCategory.AnimationSpeed = 200;
            this.btnEditCategory.AutoGenerateColors = false;
            this.btnEditCategory.AutoRoundBorders = false;
            this.btnEditCategory.AutoSizeLeftIcon = true;
            this.btnEditCategory.AutoSizeRightIcon = true;
            this.btnEditCategory.BackColor = System.Drawing.Color.Transparent;
            this.btnEditCategory.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnEditCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditCategory.BackgroundImage")));
            this.btnEditCategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditCategory.ButtonText = "Sửa";
            this.btnEditCategory.ButtonTextMarginLeft = 0;
            this.btnEditCategory.ColorContrastOnClick = 45;
            this.btnEditCategory.ColorContrastOnHover = 45;
            this.btnEditCategory.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnEditCategory.CustomizableEdges = borderEdges3;
            this.btnEditCategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditCategory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditCategory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditCategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEditCategory.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnEditCategory.ForeColor = System.Drawing.Color.White;
            this.btnEditCategory.IconLeft = null;
            this.btnEditCategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditCategory.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnEditCategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEditCategory.IconMarginLeft = 11;
            this.btnEditCategory.IconPadding = 10;
            this.btnEditCategory.IconRight = null;
            this.btnEditCategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditCategory.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnEditCategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEditCategory.IconSize = 25;
            this.btnEditCategory.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnEditCategory.IdleBorderRadius = 3;
            this.btnEditCategory.IdleBorderThickness = 1;
            this.btnEditCategory.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnEditCategory.IdleIconLeftImage = null;
            this.btnEditCategory.IdleIconRightImage = null;
            this.btnEditCategory.IndicateFocus = false;
            this.btnEditCategory.Location = new System.Drawing.Point(546, 40);
            this.btnEditCategory.Margin = new System.Windows.Forms.Padding(0);
            this.btnEditCategory.Name = "btnEditCategory";
            this.btnEditCategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditCategory.OnDisabledState.BorderRadius = 3;
            this.btnEditCategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditCategory.OnDisabledState.BorderThickness = 1;
            this.btnEditCategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditCategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditCategory.OnDisabledState.IconLeftImage = null;
            this.btnEditCategory.OnDisabledState.IconRightImage = null;
            this.btnEditCategory.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnEditCategory.onHoverState.BorderRadius = 3;
            this.btnEditCategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditCategory.onHoverState.BorderThickness = 1;
            this.btnEditCategory.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnEditCategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEditCategory.onHoverState.IconLeftImage = null;
            this.btnEditCategory.onHoverState.IconRightImage = null;
            this.btnEditCategory.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnEditCategory.OnIdleState.BorderRadius = 3;
            this.btnEditCategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditCategory.OnIdleState.BorderThickness = 1;
            this.btnEditCategory.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnEditCategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEditCategory.OnIdleState.IconLeftImage = null;
            this.btnEditCategory.OnIdleState.IconRightImage = null;
            this.btnEditCategory.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnEditCategory.OnPressedState.BorderRadius = 3;
            this.btnEditCategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditCategory.OnPressedState.BorderThickness = 1;
            this.btnEditCategory.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnEditCategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEditCategory.OnPressedState.IconLeftImage = null;
            this.btnEditCategory.OnPressedState.IconRightImage = null;
            this.btnEditCategory.Size = new System.Drawing.Size(110, 28);
            this.btnEditCategory.TabIndex = 42;
            this.btnEditCategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditCategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditCategory.TextMarginLeft = 0;
            this.btnEditCategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEditCategory.UseDefaultRadiusAndThickness = true;
            this.btnEditCategory.Click += new System.EventHandler(this.btnEditCategory_Click);
            // 
            // txtCategoryID
            // 
            this.txtCategoryID.AcceptsReturn = false;
            this.txtCategoryID.AcceptsTab = false;
            this.txtCategoryID.AnimationSpeed = 200;
            this.txtCategoryID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCategoryID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCategoryID.AutoSizeHeight = true;
            this.txtCategoryID.BackColor = System.Drawing.Color.Transparent;
            this.txtCategoryID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCategoryID.BackgroundImage")));
            this.txtCategoryID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCategoryID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtCategoryID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCategoryID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCategoryID.BorderRadius = 1;
            this.txtCategoryID.BorderThickness = 1;
            this.txtCategoryID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCategoryID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCategoryID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategoryID.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtCategoryID.DefaultText = "";
            this.txtCategoryID.Enabled = false;
            this.txtCategoryID.FillColor = System.Drawing.Color.White;
            this.txtCategoryID.HideSelection = true;
            this.txtCategoryID.IconLeft = null;
            this.txtCategoryID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategoryID.IconPadding = 10;
            this.txtCategoryID.IconRight = null;
            this.txtCategoryID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategoryID.Lines = new string[0];
            this.txtCategoryID.Location = new System.Drawing.Point(201, 4);
            this.txtCategoryID.MaxLength = 10;
            this.txtCategoryID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCategoryID.Modified = false;
            this.txtCategoryID.Multiline = false;
            this.txtCategoryID.Name = "txtCategoryID";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategoryID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCategoryID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategoryID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategoryID.OnIdleState = stateProperties4;
            this.txtCategoryID.Padding = new System.Windows.Forms.Padding(3);
            this.txtCategoryID.PasswordChar = '\0';
            this.txtCategoryID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCategoryID.PlaceholderText = "1";
            this.txtCategoryID.ReadOnly = false;
            this.txtCategoryID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCategoryID.SelectedText = "";
            this.txtCategoryID.SelectionLength = 0;
            this.txtCategoryID.SelectionStart = 0;
            this.txtCategoryID.ShortcutsEnabled = true;
            this.txtCategoryID.Size = new System.Drawing.Size(190, 29);
            this.txtCategoryID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCategoryID.TabIndex = 24;
            this.txtCategoryID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCategoryID.TextMarginBottom = 0;
            this.txtCategoryID.TextMarginLeft = 5;
            this.txtCategoryID.TextMarginTop = 0;
            this.txtCategoryID.TextPlaceholder = "1";
            this.txtCategoryID.UseSystemPasswordChar = false;
            this.txtCategoryID.WordWrap = true;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(6, 6);
            this.label7.Margin = new System.Windows.Forms.Padding(5);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(95, 17);
            this.label7.TabIndex = 23;
            this.label7.Text = "Mã danh mục:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(6, 42);
            this.label3.Margin = new System.Windows.Forms.Padding(5);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(97, 17);
            this.label3.TabIndex = 20;
            this.label3.Text = "Tên danh mục:";
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Hủy bỏ";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges4;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeft = null;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRight = null;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.IdleBorderRadius = 3;
            this.btnCancel.IdleBorderThickness = 1;
            this.btnCancel.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(546, 77);
            this.btnCancel.Margin = new System.Windows.Forms.Padding(0);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 3;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnCancel.onHoverState.BorderRadius = 3;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnIdleState.BorderRadius = 3;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnPressedState.BorderRadius = 3;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(110, 28);
            this.btnCancel.TabIndex = 45;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnDeleteCategory
            // 
            this.btnDeleteCategory.AllowAnimations = true;
            this.btnDeleteCategory.AllowMouseEffects = true;
            this.btnDeleteCategory.AllowToggling = false;
            this.btnDeleteCategory.AnimationSpeed = 200;
            this.btnDeleteCategory.AutoGenerateColors = false;
            this.btnDeleteCategory.AutoRoundBorders = false;
            this.btnDeleteCategory.AutoSizeLeftIcon = true;
            this.btnDeleteCategory.AutoSizeRightIcon = true;
            this.btnDeleteCategory.BackColor = System.Drawing.Color.Transparent;
            this.btnDeleteCategory.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnDeleteCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDeleteCategory.BackgroundImage")));
            this.btnDeleteCategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteCategory.ButtonText = "Xóa";
            this.btnDeleteCategory.ButtonTextMarginLeft = 0;
            this.btnDeleteCategory.ColorContrastOnClick = 45;
            this.btnDeleteCategory.ColorContrastOnHover = 45;
            this.btnDeleteCategory.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnDeleteCategory.CustomizableEdges = borderEdges5;
            this.btnDeleteCategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDeleteCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeleteCategory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeleteCategory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeleteCategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDeleteCategory.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnDeleteCategory.ForeColor = System.Drawing.Color.White;
            this.btnDeleteCategory.IconLeft = null;
            this.btnDeleteCategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDeleteCategory.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDeleteCategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDeleteCategory.IconMarginLeft = 11;
            this.btnDeleteCategory.IconPadding = 10;
            this.btnDeleteCategory.IconRight = null;
            this.btnDeleteCategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDeleteCategory.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDeleteCategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDeleteCategory.IconSize = 25;
            this.btnDeleteCategory.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteCategory.IdleBorderRadius = 3;
            this.btnDeleteCategory.IdleBorderThickness = 1;
            this.btnDeleteCategory.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteCategory.IdleIconLeftImage = null;
            this.btnDeleteCategory.IdleIconRightImage = null;
            this.btnDeleteCategory.IndicateFocus = false;
            this.btnDeleteCategory.Location = new System.Drawing.Point(669, 40);
            this.btnDeleteCategory.Margin = new System.Windows.Forms.Padding(0);
            this.btnDeleteCategory.Name = "btnDeleteCategory";
            this.btnDeleteCategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeleteCategory.OnDisabledState.BorderRadius = 3;
            this.btnDeleteCategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteCategory.OnDisabledState.BorderThickness = 1;
            this.btnDeleteCategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeleteCategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeleteCategory.OnDisabledState.IconLeftImage = null;
            this.btnDeleteCategory.OnDisabledState.IconRightImage = null;
            this.btnDeleteCategory.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnDeleteCategory.onHoverState.BorderRadius = 3;
            this.btnDeleteCategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteCategory.onHoverState.BorderThickness = 1;
            this.btnDeleteCategory.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnDeleteCategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteCategory.onHoverState.IconLeftImage = null;
            this.btnDeleteCategory.onHoverState.IconRightImage = null;
            this.btnDeleteCategory.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteCategory.OnIdleState.BorderRadius = 3;
            this.btnDeleteCategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteCategory.OnIdleState.BorderThickness = 1;
            this.btnDeleteCategory.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteCategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteCategory.OnIdleState.IconLeftImage = null;
            this.btnDeleteCategory.OnIdleState.IconRightImage = null;
            this.btnDeleteCategory.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteCategory.OnPressedState.BorderRadius = 3;
            this.btnDeleteCategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteCategory.OnPressedState.BorderThickness = 1;
            this.btnDeleteCategory.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteCategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteCategory.OnPressedState.IconLeftImage = null;
            this.btnDeleteCategory.OnPressedState.IconRightImage = null;
            this.btnDeleteCategory.Size = new System.Drawing.Size(110, 28);
            this.btnDeleteCategory.TabIndex = 40;
            this.btnDeleteCategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDeleteCategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDeleteCategory.TextMarginLeft = 0;
            this.btnDeleteCategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDeleteCategory.UseDefaultRadiusAndThickness = true;
            this.btnDeleteCategory.Click += new System.EventHandler(this.btnDeleteCategory_Click);
            // 
            // txtCategoryName
            // 
            this.txtCategoryName.AcceptsReturn = false;
            this.txtCategoryName.AcceptsTab = false;
            this.txtCategoryName.AnimationSpeed = 200;
            this.txtCategoryName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCategoryName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCategoryName.AutoSizeHeight = true;
            this.txtCategoryName.BackColor = System.Drawing.Color.Transparent;
            this.txtCategoryName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCategoryName.BackgroundImage")));
            this.txtCategoryName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCategoryName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtCategoryName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCategoryName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCategoryName.BorderRadius = 1;
            this.txtCategoryName.BorderThickness = 1;
            this.txtCategoryName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCategoryName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCategoryName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategoryName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtCategoryName.DefaultText = "";
            this.txtCategoryName.FillColor = System.Drawing.Color.White;
            this.txtCategoryName.HideSelection = true;
            this.txtCategoryName.IconLeft = null;
            this.txtCategoryName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategoryName.IconPadding = 10;
            this.txtCategoryName.IconRight = null;
            this.txtCategoryName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCategoryName.Lines = new string[0];
            this.txtCategoryName.Location = new System.Drawing.Point(201, 40);
            this.txtCategoryName.MaxLength = 50;
            this.txtCategoryName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCategoryName.Modified = false;
            this.txtCategoryName.Multiline = false;
            this.txtCategoryName.Name = "txtCategoryName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategoryName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCategoryName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategoryName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCategoryName.OnIdleState = stateProperties8;
            this.txtCategoryName.Padding = new System.Windows.Forms.Padding(3);
            this.txtCategoryName.PasswordChar = '\0';
            this.txtCategoryName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCategoryName.PlaceholderText = "Công nghệ";
            this.txtCategoryName.ReadOnly = false;
            this.txtCategoryName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCategoryName.SelectedText = "";
            this.txtCategoryName.SelectionLength = 0;
            this.txtCategoryName.SelectionStart = 0;
            this.txtCategoryName.ShortcutsEnabled = true;
            this.txtCategoryName.Size = new System.Drawing.Size(190, 29);
            this.txtCategoryName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCategoryName.TabIndex = 0;
            this.txtCategoryName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCategoryName.TextMarginBottom = 0;
            this.txtCategoryName.TextMarginLeft = 5;
            this.txtCategoryName.TextMarginTop = 0;
            this.txtCategoryName.TextPlaceholder = "Công nghệ";
            this.txtCategoryName.UseSystemPasswordChar = false;
            this.txtCategoryName.WordWrap = true;
            // 
            // btnAddCategory
            // 
            this.btnAddCategory.AllowAnimations = true;
            this.btnAddCategory.AllowMouseEffects = true;
            this.btnAddCategory.AllowToggling = false;
            this.btnAddCategory.AnimationSpeed = 200;
            this.btnAddCategory.AutoGenerateColors = false;
            this.btnAddCategory.AutoRoundBorders = false;
            this.btnAddCategory.AutoSizeLeftIcon = true;
            this.btnAddCategory.AutoSizeRightIcon = true;
            this.btnAddCategory.BackColor = System.Drawing.Color.Transparent;
            this.btnAddCategory.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnAddCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddCategory.BackgroundImage")));
            this.btnAddCategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCategory.ButtonText = "Thêm";
            this.btnAddCategory.ButtonTextMarginLeft = 0;
            this.btnAddCategory.ColorContrastOnClick = 45;
            this.btnAddCategory.ColorContrastOnHover = 45;
            this.btnAddCategory.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnAddCategory.CustomizableEdges = borderEdges6;
            this.btnAddCategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddCategory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddCategory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddCategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAddCategory.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnAddCategory.ForeColor = System.Drawing.Color.White;
            this.btnAddCategory.IconLeft = null;
            this.btnAddCategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddCategory.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAddCategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddCategory.IconMarginLeft = 11;
            this.btnAddCategory.IconPadding = 10;
            this.btnAddCategory.IconRight = null;
            this.btnAddCategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddCategory.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAddCategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddCategory.IconSize = 25;
            this.btnAddCategory.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnAddCategory.IdleBorderRadius = 3;
            this.btnAddCategory.IdleBorderThickness = 1;
            this.btnAddCategory.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnAddCategory.IdleIconLeftImage = null;
            this.btnAddCategory.IdleIconRightImage = null;
            this.btnAddCategory.IndicateFocus = false;
            this.btnAddCategory.Location = new System.Drawing.Point(423, 40);
            this.btnAddCategory.Margin = new System.Windows.Forms.Padding(0);
            this.btnAddCategory.Name = "btnAddCategory";
            this.btnAddCategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddCategory.OnDisabledState.BorderRadius = 3;
            this.btnAddCategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCategory.OnDisabledState.BorderThickness = 1;
            this.btnAddCategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddCategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddCategory.OnDisabledState.IconLeftImage = null;
            this.btnAddCategory.OnDisabledState.IconRightImage = null;
            this.btnAddCategory.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnAddCategory.onHoverState.BorderRadius = 3;
            this.btnAddCategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCategory.onHoverState.BorderThickness = 1;
            this.btnAddCategory.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnAddCategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAddCategory.onHoverState.IconLeftImage = null;
            this.btnAddCategory.onHoverState.IconRightImage = null;
            this.btnAddCategory.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnAddCategory.OnIdleState.BorderRadius = 3;
            this.btnAddCategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCategory.OnIdleState.BorderThickness = 1;
            this.btnAddCategory.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnAddCategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddCategory.OnIdleState.IconLeftImage = null;
            this.btnAddCategory.OnIdleState.IconRightImage = null;
            this.btnAddCategory.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnAddCategory.OnPressedState.BorderRadius = 3;
            this.btnAddCategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAddCategory.OnPressedState.BorderThickness = 1;
            this.btnAddCategory.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnAddCategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAddCategory.OnPressedState.IconLeftImage = null;
            this.btnAddCategory.OnPressedState.IconRightImage = null;
            this.btnAddCategory.Size = new System.Drawing.Size(110, 28);
            this.btnAddCategory.TabIndex = 41;
            this.btnAddCategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAddCategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddCategory.TextMarginLeft = 0;
            this.btnAddCategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAddCategory.UseDefaultRadiusAndThickness = true;
            this.btnAddCategory.Click += new System.EventHandler(this.btnAddCategory_Click);
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.AutoSize = true;
            this.tableLayoutPanel2.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tableLayoutPanel2.CellBorderStyle = System.Windows.Forms.TableLayoutPanelCellBorderStyle.Single;
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Controls.Add(this.label4, 0, 3);
            this.tableLayoutPanel2.Controls.Add(this.label2, 0, 2);
            this.tableLayoutPanel2.Controls.Add(this.txtCategoryID, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.label7, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.label3, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.txtCategoryName, 1, 1);
            this.tableLayoutPanel2.Controls.Add(this.txtProductCount, 1, 2);
            this.tableLayoutPanel2.Controls.Add(this.txtTotalQuantityInStock, 1, 3);
            this.tableLayoutPanel2.Location = new System.Drawing.Point(11, 40);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 4;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(395, 145);
            this.tableLayoutPanel2.TabIndex = 37;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(6, 114);
            this.label4.Margin = new System.Windows.Forms.Padding(5);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(164, 17);
            this.label4.TabIndex = 27;
            this.label4.Text = "Tổng số lượng trong kho:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(6, 78);
            this.label2.Margin = new System.Windows.Forms.Padding(5);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(128, 17);
            this.label2.TabIndex = 25;
            this.label2.Text = "Số lượng mặt hàng:";
            // 
            // txtProductCount
            // 
            this.txtProductCount.AcceptsReturn = false;
            this.txtProductCount.AcceptsTab = false;
            this.txtProductCount.AnimationSpeed = 200;
            this.txtProductCount.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtProductCount.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtProductCount.AutoSizeHeight = true;
            this.txtProductCount.BackColor = System.Drawing.Color.Transparent;
            this.txtProductCount.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtProductCount.BackgroundImage")));
            this.txtProductCount.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtProductCount.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtProductCount.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtProductCount.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtProductCount.BorderRadius = 1;
            this.txtProductCount.BorderThickness = 1;
            this.txtProductCount.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtProductCount.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtProductCount.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductCount.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtProductCount.DefaultText = "";
            this.txtProductCount.Enabled = false;
            this.txtProductCount.FillColor = System.Drawing.Color.White;
            this.txtProductCount.HideSelection = true;
            this.txtProductCount.IconLeft = null;
            this.txtProductCount.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductCount.IconPadding = 10;
            this.txtProductCount.IconRight = null;
            this.txtProductCount.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtProductCount.Lines = new string[0];
            this.txtProductCount.Location = new System.Drawing.Point(201, 76);
            this.txtProductCount.MaxLength = 50;
            this.txtProductCount.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtProductCount.Modified = false;
            this.txtProductCount.Multiline = false;
            this.txtProductCount.Name = "txtProductCount";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductCount.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProductCount.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductCount.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtProductCount.OnIdleState = stateProperties12;
            this.txtProductCount.Padding = new System.Windows.Forms.Padding(3);
            this.txtProductCount.PasswordChar = '\0';
            this.txtProductCount.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtProductCount.PlaceholderText = "10";
            this.txtProductCount.ReadOnly = false;
            this.txtProductCount.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtProductCount.SelectedText = "";
            this.txtProductCount.SelectionLength = 0;
            this.txtProductCount.SelectionStart = 0;
            this.txtProductCount.ShortcutsEnabled = true;
            this.txtProductCount.Size = new System.Drawing.Size(190, 29);
            this.txtProductCount.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtProductCount.TabIndex = 26;
            this.txtProductCount.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtProductCount.TextMarginBottom = 0;
            this.txtProductCount.TextMarginLeft = 5;
            this.txtProductCount.TextMarginTop = 0;
            this.txtProductCount.TextPlaceholder = "10";
            this.txtProductCount.UseSystemPasswordChar = false;
            this.txtProductCount.WordWrap = true;
            // 
            // txtTotalQuantityInStock
            // 
            this.txtTotalQuantityInStock.AcceptsReturn = false;
            this.txtTotalQuantityInStock.AcceptsTab = false;
            this.txtTotalQuantityInStock.AnimationSpeed = 200;
            this.txtTotalQuantityInStock.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTotalQuantityInStock.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTotalQuantityInStock.AutoSizeHeight = true;
            this.txtTotalQuantityInStock.BackColor = System.Drawing.Color.Transparent;
            this.txtTotalQuantityInStock.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTotalQuantityInStock.BackgroundImage")));
            this.txtTotalQuantityInStock.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTotalQuantityInStock.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtTotalQuantityInStock.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTotalQuantityInStock.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTotalQuantityInStock.BorderRadius = 1;
            this.txtTotalQuantityInStock.BorderThickness = 1;
            this.txtTotalQuantityInStock.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTotalQuantityInStock.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTotalQuantityInStock.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTotalQuantityInStock.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtTotalQuantityInStock.DefaultText = "";
            this.txtTotalQuantityInStock.Enabled = false;
            this.txtTotalQuantityInStock.FillColor = System.Drawing.Color.White;
            this.txtTotalQuantityInStock.HideSelection = true;
            this.txtTotalQuantityInStock.IconLeft = null;
            this.txtTotalQuantityInStock.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTotalQuantityInStock.IconPadding = 10;
            this.txtTotalQuantityInStock.IconRight = null;
            this.txtTotalQuantityInStock.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTotalQuantityInStock.Lines = new string[0];
            this.txtTotalQuantityInStock.Location = new System.Drawing.Point(201, 112);
            this.txtTotalQuantityInStock.MaxLength = 50;
            this.txtTotalQuantityInStock.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTotalQuantityInStock.Modified = false;
            this.txtTotalQuantityInStock.Multiline = false;
            this.txtTotalQuantityInStock.Name = "txtTotalQuantityInStock";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTotalQuantityInStock.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTotalQuantityInStock.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTotalQuantityInStock.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTotalQuantityInStock.OnIdleState = stateProperties16;
            this.txtTotalQuantityInStock.Padding = new System.Windows.Forms.Padding(3);
            this.txtTotalQuantityInStock.PasswordChar = '\0';
            this.txtTotalQuantityInStock.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTotalQuantityInStock.PlaceholderText = "1000";
            this.txtTotalQuantityInStock.ReadOnly = false;
            this.txtTotalQuantityInStock.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTotalQuantityInStock.SelectedText = "";
            this.txtTotalQuantityInStock.SelectionLength = 0;
            this.txtTotalQuantityInStock.SelectionStart = 0;
            this.txtTotalQuantityInStock.ShortcutsEnabled = true;
            this.txtTotalQuantityInStock.Size = new System.Drawing.Size(190, 29);
            this.txtTotalQuantityInStock.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTotalQuantityInStock.TabIndex = 28;
            this.txtTotalQuantityInStock.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTotalQuantityInStock.TextMarginBottom = 0;
            this.txtTotalQuantityInStock.TextMarginLeft = 5;
            this.txtTotalQuantityInStock.TextMarginTop = 0;
            this.txtTotalQuantityInStock.TextPlaceholder = "1000";
            this.txtTotalQuantityInStock.UseSystemPasswordChar = false;
            this.txtTotalQuantityInStock.WordWrap = true;
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.ColumnHeader;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Location = new System.Drawing.Point(11, 204);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.Size = new System.Drawing.Size(768, 325);
            this.dataGridView1.TabIndex = 34;
            this.dataGridView1.RowEnter += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridView1_RowEnter);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(14, 15);
            this.label1.Margin = new System.Windows.Forms.Padding(5);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(70, 17);
            this.label1.TabIndex = 52;
            this.label1.Text = "Thông tin:";
            // 
            // flowLayoutPanel3
            // 
            this.flowLayoutPanel3.AutoSize = true;
            this.flowLayoutPanel3.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.flowLayoutPanel3.Controls.Add(this.txtSearchBox);
            this.flowLayoutPanel3.Controls.Add(this.btnSearch);
            this.flowLayoutPanel3.Location = new System.Drawing.Point(423, 150);
            this.flowLayoutPanel3.Name = "flowLayoutPanel3";
            this.flowLayoutPanel3.Size = new System.Drawing.Size(355, 35);
            this.flowLayoutPanel3.TabIndex = 53;
            // 
            // txtSearchBox
            // 
            this.txtSearchBox.AcceptsReturn = false;
            this.txtSearchBox.AcceptsTab = false;
            this.txtSearchBox.AnimationSpeed = 200;
            this.txtSearchBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearchBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearchBox.AutoSizeHeight = true;
            this.txtSearchBox.BackColor = System.Drawing.Color.Transparent;
            this.txtSearchBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearchBox.BackgroundImage")));
            this.txtSearchBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSearchBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtSearchBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSearchBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSearchBox.BorderRadius = 1;
            this.txtSearchBox.BorderThickness = 1;
            this.txtSearchBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSearchBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearchBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchBox.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtSearchBox.DefaultText = "";
            this.txtSearchBox.FillColor = System.Drawing.Color.White;
            this.txtSearchBox.HideSelection = true;
            this.txtSearchBox.IconLeft = null;
            this.txtSearchBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchBox.IconPadding = 10;
            this.txtSearchBox.IconRight = null;
            this.txtSearchBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchBox.Lines = new string[0];
            this.txtSearchBox.Location = new System.Drawing.Point(3, 3);
            this.txtSearchBox.MaxLength = 50;
            this.txtSearchBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearchBox.Modified = false;
            this.txtSearchBox.Multiline = true;
            this.txtSearchBox.Name = "txtSearchBox";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearchBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchBox.OnIdleState = stateProperties20;
            this.txtSearchBox.Padding = new System.Windows.Forms.Padding(3);
            this.txtSearchBox.PasswordChar = '\0';
            this.txtSearchBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearchBox.PlaceholderText = "Nhập tên bạn muốn tìm kiếm";
            this.txtSearchBox.ReadOnly = false;
            this.txtSearchBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearchBox.SelectedText = "";
            this.txtSearchBox.SelectionLength = 0;
            this.txtSearchBox.SelectionStart = 0;
            this.txtSearchBox.ShortcutsEnabled = true;
            this.txtSearchBox.Size = new System.Drawing.Size(250, 29);
            this.txtSearchBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearchBox.TabIndex = 38;
            this.txtSearchBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtSearchBox.TextMarginBottom = 0;
            this.txtSearchBox.TextMarginLeft = 5;
            this.txtSearchBox.TextMarginTop = 0;
            this.txtSearchBox.TextPlaceholder = "Nhập tên bạn muốn tìm kiếm";
            this.txtSearchBox.UseSystemPasswordChar = false;
            this.txtSearchBox.WordWrap = true;
            // 
            // btnSearch
            // 
            this.btnSearch.AllowAnimations = true;
            this.btnSearch.AllowMouseEffects = true;
            this.btnSearch.AllowToggling = false;
            this.btnSearch.AnimationSpeed = 200;
            this.btnSearch.AutoGenerateColors = false;
            this.btnSearch.AutoRoundBorders = false;
            this.btnSearch.AutoSizeLeftIcon = true;
            this.btnSearch.AutoSizeRightIcon = true;
            this.btnSearch.BackColor = System.Drawing.Color.Transparent;
            this.btnSearch.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSearch.BackgroundImage")));
            this.btnSearch.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.ButtonText = "Tìm";
            this.btnSearch.ButtonTextMarginLeft = 0;
            this.btnSearch.ColorContrastOnClick = 45;
            this.btnSearch.ColorContrastOnHover = 45;
            this.btnSearch.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnSearch.CustomizableEdges = borderEdges7;
            this.btnSearch.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSearch.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSearch.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSearch.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSearch.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSearch.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnSearch.ForeColor = System.Drawing.Color.White;
            this.btnSearch.IconLeft = null;
            this.btnSearch.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSearch.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSearch.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSearch.IconMarginLeft = 11;
            this.btnSearch.IconPadding = 10;
            this.btnSearch.IconRight = null;
            this.btnSearch.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSearch.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSearch.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSearch.IconSize = 25;
            this.btnSearch.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.IdleBorderRadius = 3;
            this.btnSearch.IdleBorderThickness = 1;
            this.btnSearch.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.IdleIconLeftImage = null;
            this.btnSearch.IdleIconRightImage = null;
            this.btnSearch.IndicateFocus = false;
            this.btnSearch.Location = new System.Drawing.Point(266, 5);
            this.btnSearch.Margin = new System.Windows.Forms.Padding(10, 5, 3, 3);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSearch.OnDisabledState.BorderRadius = 3;
            this.btnSearch.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnDisabledState.BorderThickness = 1;
            this.btnSearch.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSearch.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSearch.OnDisabledState.IconLeftImage = null;
            this.btnSearch.OnDisabledState.IconRightImage = null;
            this.btnSearch.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnSearch.onHoverState.BorderRadius = 3;
            this.btnSearch.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.onHoverState.BorderThickness = 1;
            this.btnSearch.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnSearch.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.onHoverState.IconLeftImage = null;
            this.btnSearch.onHoverState.IconRightImage = null;
            this.btnSearch.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.OnIdleState.BorderRadius = 3;
            this.btnSearch.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnIdleState.BorderThickness = 1;
            this.btnSearch.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.OnIdleState.IconLeftImage = null;
            this.btnSearch.OnIdleState.IconRightImage = null;
            this.btnSearch.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.OnPressedState.BorderRadius = 3;
            this.btnSearch.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnPressedState.BorderThickness = 1;
            this.btnSearch.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.OnPressedState.IconLeftImage = null;
            this.btnSearch.OnPressedState.IconRightImage = null;
            this.btnSearch.Size = new System.Drawing.Size(86, 26);
            this.btnSearch.TabIndex = 37;
            this.btnSearch.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSearch.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSearch.TextMarginLeft = 0;
            this.btnSearch.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSearch.UseDefaultRadiusAndThickness = true;
            this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
            // 
            // frmManageCategory
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(791, 544);
            this.Controls.Add(this.flowLayoutPanel3);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.btnSaveCategory);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.btnEditCategory);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnDeleteCategory);
            this.Controls.Add(this.btnAddCategory);
            this.Controls.Add(this.tableLayoutPanel2);
            this.Controls.Add(this.dataGridView1);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.MaximizeBox = false;
            this.Name = "frmManageCategory";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Quản lý danh mục mặt hàng";
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.flowLayoutPanel3.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSaveCategory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEditCategory;
        private Bunifu.UI.WinForms.BunifuTextBox txtCategoryID;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDeleteCategory;
        private Bunifu.UI.WinForms.BunifuTextBox txtCategoryName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAddCategory;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.DataGridView dataGridView1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtProductCount;
        private Bunifu.UI.WinForms.BunifuTextBox txtTotalQuantityInStock;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel3;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearchBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSearch;
    }
}