namespace Shoppa
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmMain));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.btnProductView = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCartView = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHistoryView = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAccountView = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnManageTool = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLogOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.flowLayoutPanel2 = new System.Windows.Forms.FlowLayoutPanel();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.lbAccountID = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.btnHomeView = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.flowLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.panel1.SuspendLayout();
            this.flowLayoutPanel2.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.BackColor = System.Drawing.Color.Transparent;
            this.flowLayoutPanel1.Controls.Add(this.btnHomeView);
            this.flowLayoutPanel1.Controls.Add(this.btnProductView);
            this.flowLayoutPanel1.Controls.Add(this.btnCartView);
            this.flowLayoutPanel1.Controls.Add(this.btnHistoryView);
            this.flowLayoutPanel1.Controls.Add(this.btnAccountView);
            this.flowLayoutPanel1.Controls.Add(this.btnManageTool);
            this.flowLayoutPanel1.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(0, 95);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(200, 245);
            this.flowLayoutPanel1.TabIndex = 0;
            // 
            // btnProductView
            // 
            this.btnProductView.AllowAnimations = true;
            this.btnProductView.AllowMouseEffects = true;
            this.btnProductView.AllowToggling = false;
            this.btnProductView.AnimationSpeed = 200;
            this.btnProductView.AutoGenerateColors = false;
            this.btnProductView.AutoRoundBorders = false;
            this.btnProductView.AutoSizeLeftIcon = true;
            this.btnProductView.AutoSizeRightIcon = true;
            this.btnProductView.BackColor = System.Drawing.Color.Transparent;
            this.btnProductView.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnProductView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProductView.BackgroundImage")));
            this.btnProductView.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.ButtonText = "Mặt hàng";
            this.btnProductView.ButtonTextMarginLeft = 0;
            this.btnProductView.ColorContrastOnClick = 45;
            this.btnProductView.ColorContrastOnHover = 45;
            this.btnProductView.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnProductView.CustomizableEdges = borderEdges2;
            this.btnProductView.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProductView.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductView.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProductView.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProductView.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProductView.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnProductView.ForeColor = System.Drawing.Color.White;
            this.btnProductView.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnProductView.IconLeft")));
            this.btnProductView.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProductView.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProductView.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProductView.IconMarginLeft = 11;
            this.btnProductView.IconPadding = 10;
            this.btnProductView.IconRight = null;
            this.btnProductView.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProductView.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProductView.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProductView.IconSize = 25;
            this.btnProductView.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.IdleBorderRadius = 3;
            this.btnProductView.IdleBorderThickness = 1;
            this.btnProductView.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnProductView.IdleIconLeftImage")));
            this.btnProductView.IdleIconRightImage = null;
            this.btnProductView.IndicateFocus = false;
            this.btnProductView.Location = new System.Drawing.Point(0, 40);
            this.btnProductView.Margin = new System.Windows.Forms.Padding(0);
            this.btnProductView.Name = "btnProductView";
            this.btnProductView.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductView.OnDisabledState.BorderRadius = 3;
            this.btnProductView.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.OnDisabledState.BorderThickness = 1;
            this.btnProductView.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProductView.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProductView.OnDisabledState.IconLeftImage = null;
            this.btnProductView.OnDisabledState.IconRightImage = null;
            this.btnProductView.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnProductView.onHoverState.BorderRadius = 3;
            this.btnProductView.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.onHoverState.BorderThickness = 1;
            this.btnProductView.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnProductView.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProductView.onHoverState.IconLeftImage = null;
            this.btnProductView.onHoverState.IconRightImage = null;
            this.btnProductView.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.OnIdleState.BorderRadius = 3;
            this.btnProductView.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.OnIdleState.BorderThickness = 1;
            this.btnProductView.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProductView.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnProductView.OnIdleState.IconLeftImage")));
            this.btnProductView.OnIdleState.IconRightImage = null;
            this.btnProductView.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.OnPressedState.BorderRadius = 3;
            this.btnProductView.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.OnPressedState.BorderThickness = 1;
            this.btnProductView.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProductView.OnPressedState.IconLeftImage = null;
            this.btnProductView.OnPressedState.IconRightImage = null;
            this.btnProductView.Size = new System.Drawing.Size(200, 40);
            this.btnProductView.TabIndex = 4;
            this.btnProductView.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProductView.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProductView.TextMarginLeft = 0;
            this.btnProductView.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProductView.UseDefaultRadiusAndThickness = true;
            this.btnProductView.Click += new System.EventHandler(this.btnProductView_Click);
            // 
            // btnCartView
            // 
            this.btnCartView.AllowAnimations = true;
            this.btnCartView.AllowMouseEffects = true;
            this.btnCartView.AllowToggling = false;
            this.btnCartView.AnimationSpeed = 200;
            this.btnCartView.AutoGenerateColors = false;
            this.btnCartView.AutoRoundBorders = false;
            this.btnCartView.AutoSizeLeftIcon = true;
            this.btnCartView.AutoSizeRightIcon = true;
            this.btnCartView.BackColor = System.Drawing.Color.Transparent;
            this.btnCartView.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnCartView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCartView.BackgroundImage")));
            this.btnCartView.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.ButtonText = "Giỏ hàng";
            this.btnCartView.ButtonTextMarginLeft = 0;
            this.btnCartView.ColorContrastOnClick = 45;
            this.btnCartView.ColorContrastOnHover = 45;
            this.btnCartView.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnCartView.CustomizableEdges = borderEdges3;
            this.btnCartView.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCartView.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCartView.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCartView.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCartView.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCartView.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnCartView.ForeColor = System.Drawing.Color.White;
            this.btnCartView.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnCartView.IconLeft")));
            this.btnCartView.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCartView.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCartView.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCartView.IconMarginLeft = 11;
            this.btnCartView.IconPadding = 10;
            this.btnCartView.IconRight = null;
            this.btnCartView.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCartView.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCartView.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCartView.IconSize = 25;
            this.btnCartView.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.IdleBorderRadius = 3;
            this.btnCartView.IdleBorderThickness = 1;
            this.btnCartView.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCartView.IdleIconLeftImage")));
            this.btnCartView.IdleIconRightImage = null;
            this.btnCartView.IndicateFocus = false;
            this.btnCartView.Location = new System.Drawing.Point(0, 80);
            this.btnCartView.Margin = new System.Windows.Forms.Padding(0);
            this.btnCartView.Name = "btnCartView";
            this.btnCartView.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCartView.OnDisabledState.BorderRadius = 3;
            this.btnCartView.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.OnDisabledState.BorderThickness = 1;
            this.btnCartView.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCartView.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCartView.OnDisabledState.IconLeftImage = null;
            this.btnCartView.OnDisabledState.IconRightImage = null;
            this.btnCartView.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnCartView.onHoverState.BorderRadius = 3;
            this.btnCartView.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.onHoverState.BorderThickness = 1;
            this.btnCartView.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnCartView.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCartView.onHoverState.IconLeftImage = null;
            this.btnCartView.onHoverState.IconRightImage = null;
            this.btnCartView.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.OnIdleState.BorderRadius = 3;
            this.btnCartView.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.OnIdleState.BorderThickness = 1;
            this.btnCartView.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCartView.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCartView.OnIdleState.IconLeftImage")));
            this.btnCartView.OnIdleState.IconRightImage = null;
            this.btnCartView.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.OnPressedState.BorderRadius = 3;
            this.btnCartView.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.OnPressedState.BorderThickness = 1;
            this.btnCartView.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCartView.OnPressedState.IconLeftImage = null;
            this.btnCartView.OnPressedState.IconRightImage = null;
            this.btnCartView.Size = new System.Drawing.Size(200, 40);
            this.btnCartView.TabIndex = 5;
            this.btnCartView.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCartView.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCartView.TextMarginLeft = 0;
            this.btnCartView.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCartView.UseDefaultRadiusAndThickness = true;
            this.btnCartView.Click += new System.EventHandler(this.btnCartView_Click);
            // 
            // btnHistoryView
            // 
            this.btnHistoryView.AllowAnimations = true;
            this.btnHistoryView.AllowMouseEffects = true;
            this.btnHistoryView.AllowToggling = false;
            this.btnHistoryView.AnimationSpeed = 200;
            this.btnHistoryView.AutoGenerateColors = false;
            this.btnHistoryView.AutoRoundBorders = false;
            this.btnHistoryView.AutoSizeLeftIcon = true;
            this.btnHistoryView.AutoSizeRightIcon = true;
            this.btnHistoryView.BackColor = System.Drawing.Color.Transparent;
            this.btnHistoryView.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnHistoryView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHistoryView.BackgroundImage")));
            this.btnHistoryView.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistoryView.ButtonText = "Lịch sử mua hàng";
            this.btnHistoryView.ButtonTextMarginLeft = 0;
            this.btnHistoryView.ColorContrastOnClick = 45;
            this.btnHistoryView.ColorContrastOnHover = 45;
            this.btnHistoryView.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnHistoryView.CustomizableEdges = borderEdges4;
            this.btnHistoryView.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHistoryView.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHistoryView.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHistoryView.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHistoryView.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHistoryView.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnHistoryView.ForeColor = System.Drawing.Color.White;
            this.btnHistoryView.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnHistoryView.IconLeft")));
            this.btnHistoryView.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHistoryView.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHistoryView.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHistoryView.IconMarginLeft = 11;
            this.btnHistoryView.IconPadding = 10;
            this.btnHistoryView.IconRight = null;
            this.btnHistoryView.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHistoryView.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHistoryView.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHistoryView.IconSize = 25;
            this.btnHistoryView.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnHistoryView.IdleBorderRadius = 3;
            this.btnHistoryView.IdleBorderThickness = 1;
            this.btnHistoryView.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnHistoryView.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnHistoryView.IdleIconLeftImage")));
            this.btnHistoryView.IdleIconRightImage = null;
            this.btnHistoryView.IndicateFocus = false;
            this.btnHistoryView.Location = new System.Drawing.Point(0, 120);
            this.btnHistoryView.Margin = new System.Windows.Forms.Padding(0);
            this.btnHistoryView.Name = "btnHistoryView";
            this.btnHistoryView.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHistoryView.OnDisabledState.BorderRadius = 3;
            this.btnHistoryView.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistoryView.OnDisabledState.BorderThickness = 1;
            this.btnHistoryView.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHistoryView.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHistoryView.OnDisabledState.IconLeftImage = null;
            this.btnHistoryView.OnDisabledState.IconRightImage = null;
            this.btnHistoryView.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnHistoryView.onHoverState.BorderRadius = 3;
            this.btnHistoryView.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistoryView.onHoverState.BorderThickness = 1;
            this.btnHistoryView.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnHistoryView.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHistoryView.onHoverState.IconLeftImage = null;
            this.btnHistoryView.onHoverState.IconRightImage = null;
            this.btnHistoryView.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnHistoryView.OnIdleState.BorderRadius = 3;
            this.btnHistoryView.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistoryView.OnIdleState.BorderThickness = 1;
            this.btnHistoryView.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnHistoryView.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHistoryView.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnHistoryView.OnIdleState.IconLeftImage")));
            this.btnHistoryView.OnIdleState.IconRightImage = null;
            this.btnHistoryView.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnHistoryView.OnPressedState.BorderRadius = 3;
            this.btnHistoryView.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHistoryView.OnPressedState.BorderThickness = 1;
            this.btnHistoryView.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnHistoryView.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHistoryView.OnPressedState.IconLeftImage = null;
            this.btnHistoryView.OnPressedState.IconRightImage = null;
            this.btnHistoryView.Size = new System.Drawing.Size(200, 40);
            this.btnHistoryView.TabIndex = 6;
            this.btnHistoryView.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHistoryView.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHistoryView.TextMarginLeft = 0;
            this.btnHistoryView.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHistoryView.UseDefaultRadiusAndThickness = true;
            this.btnHistoryView.Click += new System.EventHandler(this.btnHistoryView_Click);
            // 
            // btnAccountView
            // 
            this.btnAccountView.AllowAnimations = true;
            this.btnAccountView.AllowMouseEffects = true;
            this.btnAccountView.AllowToggling = false;
            this.btnAccountView.AnimationSpeed = 200;
            this.btnAccountView.AutoGenerateColors = false;
            this.btnAccountView.AutoRoundBorders = false;
            this.btnAccountView.AutoSizeLeftIcon = true;
            this.btnAccountView.AutoSizeRightIcon = true;
            this.btnAccountView.BackColor = System.Drawing.Color.Transparent;
            this.btnAccountView.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnAccountView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAccountView.BackgroundImage")));
            this.btnAccountView.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountView.ButtonText = "Thông tin cá nhân";
            this.btnAccountView.ButtonTextMarginLeft = 0;
            this.btnAccountView.ColorContrastOnClick = 45;
            this.btnAccountView.ColorContrastOnHover = 45;
            this.btnAccountView.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnAccountView.CustomizableEdges = borderEdges5;
            this.btnAccountView.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAccountView.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAccountView.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAccountView.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAccountView.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAccountView.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnAccountView.ForeColor = System.Drawing.Color.White;
            this.btnAccountView.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnAccountView.IconLeft")));
            this.btnAccountView.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAccountView.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAccountView.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAccountView.IconMarginLeft = 11;
            this.btnAccountView.IconPadding = 10;
            this.btnAccountView.IconRight = null;
            this.btnAccountView.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAccountView.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAccountView.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAccountView.IconSize = 25;
            this.btnAccountView.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnAccountView.IdleBorderRadius = 3;
            this.btnAccountView.IdleBorderThickness = 1;
            this.btnAccountView.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnAccountView.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAccountView.IdleIconLeftImage")));
            this.btnAccountView.IdleIconRightImage = null;
            this.btnAccountView.IndicateFocus = false;
            this.btnAccountView.Location = new System.Drawing.Point(0, 160);
            this.btnAccountView.Margin = new System.Windows.Forms.Padding(0);
            this.btnAccountView.Name = "btnAccountView";
            this.btnAccountView.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAccountView.OnDisabledState.BorderRadius = 3;
            this.btnAccountView.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountView.OnDisabledState.BorderThickness = 1;
            this.btnAccountView.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAccountView.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAccountView.OnDisabledState.IconLeftImage = null;
            this.btnAccountView.OnDisabledState.IconRightImage = null;
            this.btnAccountView.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnAccountView.onHoverState.BorderRadius = 3;
            this.btnAccountView.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountView.onHoverState.BorderThickness = 1;
            this.btnAccountView.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnAccountView.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAccountView.onHoverState.IconLeftImage = null;
            this.btnAccountView.onHoverState.IconRightImage = null;
            this.btnAccountView.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnAccountView.OnIdleState.BorderRadius = 3;
            this.btnAccountView.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountView.OnIdleState.BorderThickness = 1;
            this.btnAccountView.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnAccountView.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAccountView.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAccountView.OnIdleState.IconLeftImage")));
            this.btnAccountView.OnIdleState.IconRightImage = null;
            this.btnAccountView.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnAccountView.OnPressedState.BorderRadius = 3;
            this.btnAccountView.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccountView.OnPressedState.BorderThickness = 1;
            this.btnAccountView.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnAccountView.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAccountView.OnPressedState.IconLeftImage = null;
            this.btnAccountView.OnPressedState.IconRightImage = null;
            this.btnAccountView.Size = new System.Drawing.Size(200, 40);
            this.btnAccountView.TabIndex = 7;
            this.btnAccountView.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAccountView.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAccountView.TextMarginLeft = 0;
            this.btnAccountView.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAccountView.UseDefaultRadiusAndThickness = true;
            this.btnAccountView.Click += new System.EventHandler(this.btnAccountView_Click);
            // 
            // btnManageTool
            // 
            this.btnManageTool.AllowAnimations = true;
            this.btnManageTool.AllowMouseEffects = true;
            this.btnManageTool.AllowToggling = false;
            this.btnManageTool.AnimationSpeed = 200;
            this.btnManageTool.AutoGenerateColors = false;
            this.btnManageTool.AutoRoundBorders = false;
            this.btnManageTool.AutoSizeLeftIcon = true;
            this.btnManageTool.AutoSizeRightIcon = true;
            this.btnManageTool.BackColor = System.Drawing.Color.Transparent;
            this.btnManageTool.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnManageTool.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnManageTool.BackgroundImage")));
            this.btnManageTool.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTool.ButtonText = "Công cụ quản lý";
            this.btnManageTool.ButtonTextMarginLeft = 0;
            this.btnManageTool.ColorContrastOnClick = 45;
            this.btnManageTool.ColorContrastOnHover = 45;
            this.btnManageTool.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnManageTool.CustomizableEdges = borderEdges6;
            this.btnManageTool.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnManageTool.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageTool.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageTool.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageTool.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnManageTool.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnManageTool.ForeColor = System.Drawing.Color.White;
            this.btnManageTool.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnManageTool.IconLeft")));
            this.btnManageTool.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageTool.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnManageTool.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnManageTool.IconMarginLeft = 11;
            this.btnManageTool.IconPadding = 10;
            this.btnManageTool.IconRight = null;
            this.btnManageTool.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageTool.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnManageTool.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnManageTool.IconSize = 25;
            this.btnManageTool.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnManageTool.IdleBorderRadius = 3;
            this.btnManageTool.IdleBorderThickness = 1;
            this.btnManageTool.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnManageTool.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnManageTool.IdleIconLeftImage")));
            this.btnManageTool.IdleIconRightImage = null;
            this.btnManageTool.IndicateFocus = false;
            this.btnManageTool.Location = new System.Drawing.Point(0, 200);
            this.btnManageTool.Margin = new System.Windows.Forms.Padding(0);
            this.btnManageTool.Name = "btnManageTool";
            this.btnManageTool.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageTool.OnDisabledState.BorderRadius = 3;
            this.btnManageTool.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTool.OnDisabledState.BorderThickness = 1;
            this.btnManageTool.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageTool.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageTool.OnDisabledState.IconLeftImage = null;
            this.btnManageTool.OnDisabledState.IconRightImage = null;
            this.btnManageTool.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnManageTool.onHoverState.BorderRadius = 3;
            this.btnManageTool.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTool.onHoverState.BorderThickness = 1;
            this.btnManageTool.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnManageTool.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnManageTool.onHoverState.IconLeftImage = null;
            this.btnManageTool.onHoverState.IconRightImage = null;
            this.btnManageTool.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnManageTool.OnIdleState.BorderRadius = 3;
            this.btnManageTool.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTool.OnIdleState.BorderThickness = 1;
            this.btnManageTool.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnManageTool.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnManageTool.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnManageTool.OnIdleState.IconLeftImage")));
            this.btnManageTool.OnIdleState.IconRightImage = null;
            this.btnManageTool.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnManageTool.OnPressedState.BorderRadius = 3;
            this.btnManageTool.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageTool.OnPressedState.BorderThickness = 1;
            this.btnManageTool.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnManageTool.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnManageTool.OnPressedState.IconLeftImage = null;
            this.btnManageTool.OnPressedState.IconRightImage = null;
            this.btnManageTool.Size = new System.Drawing.Size(200, 40);
            this.btnManageTool.TabIndex = 9;
            this.btnManageTool.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnManageTool.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnManageTool.TextMarginLeft = 0;
            this.btnManageTool.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnManageTool.UseDefaultRadiusAndThickness = true;
            this.btnManageTool.Click += new System.EventHandler(this.btnManageTool_Click);
            // 
            // btnLogOut
            // 
            this.btnLogOut.AllowAnimations = true;
            this.btnLogOut.AllowMouseEffects = true;
            this.btnLogOut.AllowToggling = false;
            this.btnLogOut.AnimationSpeed = 200;
            this.btnLogOut.AutoGenerateColors = false;
            this.btnLogOut.AutoRoundBorders = false;
            this.btnLogOut.AutoSizeLeftIcon = true;
            this.btnLogOut.AutoSizeRightIcon = true;
            this.btnLogOut.BackColor = System.Drawing.Color.Transparent;
            this.btnLogOut.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnLogOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogOut.BackgroundImage")));
            this.btnLogOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.ButtonText = "Đăng xuất";
            this.btnLogOut.ButtonTextMarginLeft = 0;
            this.btnLogOut.ColorContrastOnClick = 45;
            this.btnLogOut.ColorContrastOnHover = 45;
            this.btnLogOut.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnLogOut.CustomizableEdges = borderEdges7;
            this.btnLogOut.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogOut.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogOut.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogOut.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLogOut.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnLogOut.ForeColor = System.Drawing.Color.White;
            this.btnLogOut.IconLeft = null;
            this.btnLogOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogOut.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLogOut.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLogOut.IconMarginLeft = 11;
            this.btnLogOut.IconPadding = 10;
            this.btnLogOut.IconRight = null;
            this.btnLogOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogOut.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLogOut.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogOut.IconSize = 25;
            this.btnLogOut.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.IdleBorderRadius = 3;
            this.btnLogOut.IdleBorderThickness = 1;
            this.btnLogOut.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.IdleIconLeftImage = null;
            this.btnLogOut.IdleIconRightImage = null;
            this.btnLogOut.IndicateFocus = false;
            this.btnLogOut.Location = new System.Drawing.Point(0, 33);
            this.btnLogOut.Margin = new System.Windows.Forms.Padding(0);
            this.btnLogOut.Name = "btnLogOut";
            this.btnLogOut.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogOut.OnDisabledState.BorderRadius = 3;
            this.btnLogOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.OnDisabledState.BorderThickness = 1;
            this.btnLogOut.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogOut.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogOut.OnDisabledState.IconLeftImage = null;
            this.btnLogOut.OnDisabledState.IconRightImage = null;
            this.btnLogOut.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnLogOut.onHoverState.BorderRadius = 3;
            this.btnLogOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.onHoverState.BorderThickness = 1;
            this.btnLogOut.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnLogOut.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLogOut.onHoverState.IconLeftImage = null;
            this.btnLogOut.onHoverState.IconRightImage = null;
            this.btnLogOut.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.OnIdleState.BorderRadius = 3;
            this.btnLogOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.OnIdleState.BorderThickness = 1;
            this.btnLogOut.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLogOut.OnIdleState.IconLeftImage = null;
            this.btnLogOut.OnIdleState.IconRightImage = null;
            this.btnLogOut.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.OnPressedState.BorderRadius = 3;
            this.btnLogOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.OnPressedState.BorderThickness = 1;
            this.btnLogOut.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogOut.OnPressedState.IconLeftImage = null;
            this.btnLogOut.OnPressedState.IconRightImage = null;
            this.btnLogOut.Size = new System.Drawing.Size(200, 40);
            this.btnLogOut.TabIndex = 9;
            this.btnLogOut.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogOut.TextMarginLeft = 0;
            this.btnLogOut.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLogOut.UseDefaultRadiusAndThickness = true;
            this.btnLogOut.Click += new System.EventHandler(this.btnLogOut_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(24, 7);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(156, 70);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 10;
            this.pictureBox1.TabStop = false;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.BlueViolet;
            this.panel1.Controls.Add(this.flowLayoutPanel2);
            this.panel1.Controls.Add(this.flowLayoutPanel1);
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(200, 450);
            this.panel1.TabIndex = 11;
            // 
            // flowLayoutPanel2
            // 
            this.flowLayoutPanel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(164)))), ((int)(((byte)(109)))), ((int)(((byte)(231)))));
            this.flowLayoutPanel2.Controls.Add(this.tableLayoutPanel1);
            this.flowLayoutPanel2.Controls.Add(this.btnLogOut);
            this.flowLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.flowLayoutPanel2.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flowLayoutPanel2.Location = new System.Drawing.Point(0, 377);
            this.flowLayoutPanel2.Margin = new System.Windows.Forms.Padding(0);
            this.flowLayoutPanel2.Name = "flowLayoutPanel2";
            this.flowLayoutPanel2.Size = new System.Drawing.Size(200, 73);
            this.flowLayoutPanel2.TabIndex = 13;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.lbAccountID, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.label3, 0, 0);
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(200, 33);
            this.tableLayoutPanel1.TabIndex = 12;
            // 
            // lbAccountID
            // 
            this.lbAccountID.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.lbAccountID.AutoSize = true;
            this.lbAccountID.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbAccountID.ForeColor = System.Drawing.Color.White;
            this.lbAccountID.Location = new System.Drawing.Point(110, 8);
            this.lbAccountID.Name = "lbAccountID";
            this.lbAccountID.Size = new System.Drawing.Size(80, 17);
            this.lbAccountID.TabIndex = 27;
            this.lbAccountID.Text = "doandat943";
            // 
            // label3
            // 
            this.label3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Indigo;
            this.label3.Location = new System.Drawing.Point(15, 8);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(69, 17);
            this.label3.TabIndex = 26;
            this.label3.Text = "Tài khoản:";
            // 
            // btnHomeView
            // 
            this.btnHomeView.AllowAnimations = true;
            this.btnHomeView.AllowMouseEffects = true;
            this.btnHomeView.AllowToggling = false;
            this.btnHomeView.AnimationSpeed = 200;
            this.btnHomeView.AutoGenerateColors = false;
            this.btnHomeView.AutoRoundBorders = false;
            this.btnHomeView.AutoSizeLeftIcon = true;
            this.btnHomeView.AutoSizeRightIcon = true;
            this.btnHomeView.BackColor = System.Drawing.Color.Transparent;
            this.btnHomeView.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnHomeView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHomeView.BackgroundImage")));
            this.btnHomeView.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHomeView.ButtonText = "Trang chủ";
            this.btnHomeView.ButtonTextMarginLeft = 0;
            this.btnHomeView.ColorContrastOnClick = 45;
            this.btnHomeView.ColorContrastOnHover = 45;
            this.btnHomeView.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnHomeView.CustomizableEdges = borderEdges1;
            this.btnHomeView.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHomeView.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHomeView.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHomeView.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHomeView.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHomeView.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnHomeView.ForeColor = System.Drawing.Color.White;
            this.btnHomeView.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnHomeView.IconLeft")));
            this.btnHomeView.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHomeView.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHomeView.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHomeView.IconMarginLeft = 11;
            this.btnHomeView.IconPadding = 10;
            this.btnHomeView.IconRight = null;
            this.btnHomeView.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHomeView.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHomeView.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHomeView.IconSize = 25;
            this.btnHomeView.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnHomeView.IdleBorderRadius = 3;
            this.btnHomeView.IdleBorderThickness = 1;
            this.btnHomeView.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnHomeView.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnHomeView.IdleIconLeftImage")));
            this.btnHomeView.IdleIconRightImage = null;
            this.btnHomeView.IndicateFocus = false;
            this.btnHomeView.Location = new System.Drawing.Point(0, 0);
            this.btnHomeView.Margin = new System.Windows.Forms.Padding(0);
            this.btnHomeView.Name = "btnHomeView";
            this.btnHomeView.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHomeView.OnDisabledState.BorderRadius = 3;
            this.btnHomeView.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHomeView.OnDisabledState.BorderThickness = 1;
            this.btnHomeView.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHomeView.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHomeView.OnDisabledState.IconLeftImage = null;
            this.btnHomeView.OnDisabledState.IconRightImage = null;
            this.btnHomeView.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnHomeView.onHoverState.BorderRadius = 3;
            this.btnHomeView.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHomeView.onHoverState.BorderThickness = 1;
            this.btnHomeView.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnHomeView.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHomeView.onHoverState.IconLeftImage = null;
            this.btnHomeView.onHoverState.IconRightImage = null;
            this.btnHomeView.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnHomeView.OnIdleState.BorderRadius = 3;
            this.btnHomeView.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHomeView.OnIdleState.BorderThickness = 1;
            this.btnHomeView.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnHomeView.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHomeView.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.btnHomeView.OnIdleState.IconRightImage = null;
            this.btnHomeView.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnHomeView.OnPressedState.BorderRadius = 3;
            this.btnHomeView.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHomeView.OnPressedState.BorderThickness = 1;
            this.btnHomeView.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnHomeView.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHomeView.OnPressedState.IconLeftImage = null;
            this.btnHomeView.OnPressedState.IconRightImage = null;
            this.btnHomeView.Size = new System.Drawing.Size(200, 40);
            this.btnHomeView.TabIndex = 10;
            this.btnHomeView.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHomeView.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHomeView.TextMarginLeft = 0;
            this.btnHomeView.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHomeView.UseDefaultRadiusAndThickness = true;
            this.btnHomeView.Click += new System.EventHandler(this.btnHomeView_Click);
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(870, 450);
            this.Controls.Add(this.panel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "frmMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Shoppa";
            this.SizeChanged += new System.EventHandler(this.frmMain_SizeChanged);
            this.flowLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.panel1.ResumeLayout(false);
            this.flowLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProductView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCartView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHistoryView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAccountView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogOut;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnManageTool;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.Label lbAccountID;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHomeView;
    }
}

