namespace Shoppa
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmMain));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.btnProductView = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCartView = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnUserInfoView = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnManageProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLogOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.flowLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.BackColor = System.Drawing.Color.Transparent;
            this.flowLayoutPanel1.Controls.Add(this.btnProductView);
            this.flowLayoutPanel1.Controls.Add(this.btnCartView);
            this.flowLayoutPanel1.Controls.Add(this.bunifuButton2);
            this.flowLayoutPanel1.Controls.Add(this.btnUserInfoView);
            this.flowLayoutPanel1.Controls.Add(this.btnManageProduct);
            this.flowLayoutPanel1.FlowDirection = System.Windows.Forms.FlowDirection.TopDown;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(0, 95);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(200, 312);
            this.flowLayoutPanel1.TabIndex = 0;
            // 
            // btnProductView
            // 
            this.btnProductView.AllowAnimations = true;
            this.btnProductView.AllowMouseEffects = true;
            this.btnProductView.AllowToggling = false;
            this.btnProductView.AnimationSpeed = 200;
            this.btnProductView.AutoGenerateColors = false;
            this.btnProductView.AutoRoundBorders = false;
            this.btnProductView.AutoSizeLeftIcon = true;
            this.btnProductView.AutoSizeRightIcon = true;
            this.btnProductView.BackColor = System.Drawing.Color.Transparent;
            this.btnProductView.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnProductView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProductView.BackgroundImage")));
            this.btnProductView.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.ButtonText = "Mặt hàng";
            this.btnProductView.ButtonTextMarginLeft = 0;
            this.btnProductView.ColorContrastOnClick = 45;
            this.btnProductView.ColorContrastOnHover = 45;
            this.btnProductView.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnProductView.CustomizableEdges = borderEdges1;
            this.btnProductView.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProductView.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductView.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProductView.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProductView.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProductView.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnProductView.ForeColor = System.Drawing.Color.White;
            this.btnProductView.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnProductView.IconLeft")));
            this.btnProductView.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProductView.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProductView.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProductView.IconMarginLeft = 11;
            this.btnProductView.IconPadding = 10;
            this.btnProductView.IconRight = null;
            this.btnProductView.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProductView.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnProductView.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProductView.IconSize = 25;
            this.btnProductView.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.IdleBorderRadius = 3;
            this.btnProductView.IdleBorderThickness = 1;
            this.btnProductView.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnProductView.IdleIconLeftImage")));
            this.btnProductView.IdleIconRightImage = null;
            this.btnProductView.IndicateFocus = false;
            this.btnProductView.Location = new System.Drawing.Point(0, 0);
            this.btnProductView.Margin = new System.Windows.Forms.Padding(0);
            this.btnProductView.Name = "btnProductView";
            this.btnProductView.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductView.OnDisabledState.BorderRadius = 3;
            this.btnProductView.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.OnDisabledState.BorderThickness = 1;
            this.btnProductView.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProductView.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProductView.OnDisabledState.IconLeftImage = null;
            this.btnProductView.OnDisabledState.IconRightImage = null;
            this.btnProductView.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnProductView.onHoverState.BorderRadius = 3;
            this.btnProductView.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.onHoverState.BorderThickness = 1;
            this.btnProductView.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnProductView.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProductView.onHoverState.IconLeftImage = null;
            this.btnProductView.onHoverState.IconRightImage = null;
            this.btnProductView.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.OnIdleState.BorderRadius = 3;
            this.btnProductView.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.OnIdleState.BorderThickness = 1;
            this.btnProductView.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProductView.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnProductView.OnIdleState.IconLeftImage")));
            this.btnProductView.OnIdleState.IconRightImage = null;
            this.btnProductView.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.OnPressedState.BorderRadius = 3;
            this.btnProductView.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductView.OnPressedState.BorderThickness = 1;
            this.btnProductView.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnProductView.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProductView.OnPressedState.IconLeftImage = null;
            this.btnProductView.OnPressedState.IconRightImage = null;
            this.btnProductView.Size = new System.Drawing.Size(200, 40);
            this.btnProductView.TabIndex = 4;
            this.btnProductView.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProductView.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProductView.TextMarginLeft = 0;
            this.btnProductView.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnProductView.UseDefaultRadiusAndThickness = true;
            this.btnProductView.Click += new System.EventHandler(this.btnProductView_Click);
            // 
            // btnCartView
            // 
            this.btnCartView.AllowAnimations = true;
            this.btnCartView.AllowMouseEffects = true;
            this.btnCartView.AllowToggling = false;
            this.btnCartView.AnimationSpeed = 200;
            this.btnCartView.AutoGenerateColors = false;
            this.btnCartView.AutoRoundBorders = false;
            this.btnCartView.AutoSizeLeftIcon = true;
            this.btnCartView.AutoSizeRightIcon = true;
            this.btnCartView.BackColor = System.Drawing.Color.Transparent;
            this.btnCartView.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnCartView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCartView.BackgroundImage")));
            this.btnCartView.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.ButtonText = "Giỏ hàng";
            this.btnCartView.ButtonTextMarginLeft = 0;
            this.btnCartView.ColorContrastOnClick = 45;
            this.btnCartView.ColorContrastOnHover = 45;
            this.btnCartView.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCartView.CustomizableEdges = borderEdges2;
            this.btnCartView.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCartView.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCartView.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCartView.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCartView.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCartView.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnCartView.ForeColor = System.Drawing.Color.White;
            this.btnCartView.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnCartView.IconLeft")));
            this.btnCartView.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCartView.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCartView.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCartView.IconMarginLeft = 11;
            this.btnCartView.IconPadding = 10;
            this.btnCartView.IconRight = null;
            this.btnCartView.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCartView.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCartView.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCartView.IconSize = 25;
            this.btnCartView.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.IdleBorderRadius = 3;
            this.btnCartView.IdleBorderThickness = 1;
            this.btnCartView.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCartView.IdleIconLeftImage")));
            this.btnCartView.IdleIconRightImage = null;
            this.btnCartView.IndicateFocus = false;
            this.btnCartView.Location = new System.Drawing.Point(0, 40);
            this.btnCartView.Margin = new System.Windows.Forms.Padding(0);
            this.btnCartView.Name = "btnCartView";
            this.btnCartView.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCartView.OnDisabledState.BorderRadius = 3;
            this.btnCartView.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.OnDisabledState.BorderThickness = 1;
            this.btnCartView.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCartView.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCartView.OnDisabledState.IconLeftImage = null;
            this.btnCartView.OnDisabledState.IconRightImage = null;
            this.btnCartView.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnCartView.onHoverState.BorderRadius = 3;
            this.btnCartView.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.onHoverState.BorderThickness = 1;
            this.btnCartView.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnCartView.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCartView.onHoverState.IconLeftImage = null;
            this.btnCartView.onHoverState.IconRightImage = null;
            this.btnCartView.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.OnIdleState.BorderRadius = 3;
            this.btnCartView.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.OnIdleState.BorderThickness = 1;
            this.btnCartView.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCartView.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCartView.OnIdleState.IconLeftImage")));
            this.btnCartView.OnIdleState.IconRightImage = null;
            this.btnCartView.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.OnPressedState.BorderRadius = 3;
            this.btnCartView.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCartView.OnPressedState.BorderThickness = 1;
            this.btnCartView.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCartView.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCartView.OnPressedState.IconLeftImage = null;
            this.btnCartView.OnPressedState.IconRightImage = null;
            this.btnCartView.Size = new System.Drawing.Size(200, 40);
            this.btnCartView.TabIndex = 5;
            this.btnCartView.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCartView.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCartView.TextMarginLeft = 0;
            this.btnCartView.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnCartView.UseDefaultRadiusAndThickness = true;
            this.btnCartView.Click += new System.EventHandler(this.btnCartView_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.BlueViolet;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Lịch sử mua hàng";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges3;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeft = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.IconLeft")));
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRight = null;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton2.IdleBorderRadius = 3;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton2.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.IdleIconLeftImage")));
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(0, 80);
            this.bunifuButton2.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 3;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.bunifuButton2.onHoverState.BorderRadius = 3;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton2.OnIdleState.BorderRadius = 3;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.OnIdleState.IconLeftImage")));
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton2.OnPressedState.BorderRadius = 3;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(200, 40);
            this.bunifuButton2.TabIndex = 6;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            // 
            // btnUserInfoView
            // 
            this.btnUserInfoView.AllowAnimations = true;
            this.btnUserInfoView.AllowMouseEffects = true;
            this.btnUserInfoView.AllowToggling = false;
            this.btnUserInfoView.AnimationSpeed = 200;
            this.btnUserInfoView.AutoGenerateColors = false;
            this.btnUserInfoView.AutoRoundBorders = false;
            this.btnUserInfoView.AutoSizeLeftIcon = true;
            this.btnUserInfoView.AutoSizeRightIcon = true;
            this.btnUserInfoView.BackColor = System.Drawing.Color.Transparent;
            this.btnUserInfoView.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnUserInfoView.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUserInfoView.BackgroundImage")));
            this.btnUserInfoView.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserInfoView.ButtonText = "Thông tin cá nhân";
            this.btnUserInfoView.ButtonTextMarginLeft = 0;
            this.btnUserInfoView.ColorContrastOnClick = 45;
            this.btnUserInfoView.ColorContrastOnHover = 45;
            this.btnUserInfoView.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnUserInfoView.CustomizableEdges = borderEdges4;
            this.btnUserInfoView.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUserInfoView.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUserInfoView.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUserInfoView.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUserInfoView.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUserInfoView.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnUserInfoView.ForeColor = System.Drawing.Color.White;
            this.btnUserInfoView.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnUserInfoView.IconLeft")));
            this.btnUserInfoView.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUserInfoView.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnUserInfoView.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUserInfoView.IconMarginLeft = 11;
            this.btnUserInfoView.IconPadding = 10;
            this.btnUserInfoView.IconRight = null;
            this.btnUserInfoView.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUserInfoView.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnUserInfoView.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUserInfoView.IconSize = 25;
            this.btnUserInfoView.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnUserInfoView.IdleBorderRadius = 3;
            this.btnUserInfoView.IdleBorderThickness = 1;
            this.btnUserInfoView.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnUserInfoView.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnUserInfoView.IdleIconLeftImage")));
            this.btnUserInfoView.IdleIconRightImage = null;
            this.btnUserInfoView.IndicateFocus = false;
            this.btnUserInfoView.Location = new System.Drawing.Point(0, 120);
            this.btnUserInfoView.Margin = new System.Windows.Forms.Padding(0);
            this.btnUserInfoView.Name = "btnUserInfoView";
            this.btnUserInfoView.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUserInfoView.OnDisabledState.BorderRadius = 3;
            this.btnUserInfoView.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserInfoView.OnDisabledState.BorderThickness = 1;
            this.btnUserInfoView.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUserInfoView.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUserInfoView.OnDisabledState.IconLeftImage = null;
            this.btnUserInfoView.OnDisabledState.IconRightImage = null;
            this.btnUserInfoView.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnUserInfoView.onHoverState.BorderRadius = 3;
            this.btnUserInfoView.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserInfoView.onHoverState.BorderThickness = 1;
            this.btnUserInfoView.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnUserInfoView.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUserInfoView.onHoverState.IconLeftImage = null;
            this.btnUserInfoView.onHoverState.IconRightImage = null;
            this.btnUserInfoView.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnUserInfoView.OnIdleState.BorderRadius = 3;
            this.btnUserInfoView.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserInfoView.OnIdleState.BorderThickness = 1;
            this.btnUserInfoView.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnUserInfoView.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUserInfoView.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnUserInfoView.OnIdleState.IconLeftImage")));
            this.btnUserInfoView.OnIdleState.IconRightImage = null;
            this.btnUserInfoView.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnUserInfoView.OnPressedState.BorderRadius = 3;
            this.btnUserInfoView.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUserInfoView.OnPressedState.BorderThickness = 1;
            this.btnUserInfoView.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnUserInfoView.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUserInfoView.OnPressedState.IconLeftImage = null;
            this.btnUserInfoView.OnPressedState.IconRightImage = null;
            this.btnUserInfoView.Size = new System.Drawing.Size(200, 40);
            this.btnUserInfoView.TabIndex = 7;
            this.btnUserInfoView.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUserInfoView.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUserInfoView.TextMarginLeft = 0;
            this.btnUserInfoView.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnUserInfoView.UseDefaultRadiusAndThickness = true;
            this.btnUserInfoView.Click += new System.EventHandler(this.btnUserInfoView_Click);
            // 
            // btnManageProduct
            // 
            this.btnManageProduct.AllowAnimations = true;
            this.btnManageProduct.AllowMouseEffects = true;
            this.btnManageProduct.AllowToggling = false;
            this.btnManageProduct.AnimationSpeed = 200;
            this.btnManageProduct.AutoGenerateColors = false;
            this.btnManageProduct.AutoRoundBorders = false;
            this.btnManageProduct.AutoSizeLeftIcon = true;
            this.btnManageProduct.AutoSizeRightIcon = true;
            this.btnManageProduct.BackColor = System.Drawing.Color.Transparent;
            this.btnManageProduct.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnManageProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnManageProduct.BackgroundImage")));
            this.btnManageProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageProduct.ButtonText = "Quản lý mặt hàng";
            this.btnManageProduct.ButtonTextMarginLeft = 0;
            this.btnManageProduct.ColorContrastOnClick = 45;
            this.btnManageProduct.ColorContrastOnHover = 45;
            this.btnManageProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnManageProduct.CustomizableEdges = borderEdges5;
            this.btnManageProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnManageProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnManageProduct.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnManageProduct.ForeColor = System.Drawing.Color.White;
            this.btnManageProduct.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnManageProduct.IconLeft")));
            this.btnManageProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageProduct.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnManageProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnManageProduct.IconMarginLeft = 11;
            this.btnManageProduct.IconPadding = 10;
            this.btnManageProduct.IconRight = null;
            this.btnManageProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageProduct.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnManageProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnManageProduct.IconSize = 25;
            this.btnManageProduct.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnManageProduct.IdleBorderRadius = 3;
            this.btnManageProduct.IdleBorderThickness = 1;
            this.btnManageProduct.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnManageProduct.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnManageProduct.IdleIconLeftImage")));
            this.btnManageProduct.IdleIconRightImage = null;
            this.btnManageProduct.IndicateFocus = false;
            this.btnManageProduct.Location = new System.Drawing.Point(0, 160);
            this.btnManageProduct.Margin = new System.Windows.Forms.Padding(0);
            this.btnManageProduct.Name = "btnManageProduct";
            this.btnManageProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageProduct.OnDisabledState.BorderRadius = 3;
            this.btnManageProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageProduct.OnDisabledState.BorderThickness = 1;
            this.btnManageProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageProduct.OnDisabledState.IconLeftImage = null;
            this.btnManageProduct.OnDisabledState.IconRightImage = null;
            this.btnManageProduct.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnManageProduct.onHoverState.BorderRadius = 3;
            this.btnManageProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageProduct.onHoverState.BorderThickness = 1;
            this.btnManageProduct.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnManageProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnManageProduct.onHoverState.IconLeftImage = null;
            this.btnManageProduct.onHoverState.IconRightImage = null;
            this.btnManageProduct.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnManageProduct.OnIdleState.BorderRadius = 3;
            this.btnManageProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageProduct.OnIdleState.BorderThickness = 1;
            this.btnManageProduct.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnManageProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnManageProduct.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.OnIdleState.IconLeftImage")));
            this.btnManageProduct.OnIdleState.IconRightImage = null;
            this.btnManageProduct.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnManageProduct.OnPressedState.BorderRadius = 3;
            this.btnManageProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageProduct.OnPressedState.BorderThickness = 1;
            this.btnManageProduct.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnManageProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnManageProduct.OnPressedState.IconLeftImage = null;
            this.btnManageProduct.OnPressedState.IconRightImage = null;
            this.btnManageProduct.Size = new System.Drawing.Size(200, 40);
            this.btnManageProduct.TabIndex = 8;
            this.btnManageProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnManageProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnManageProduct.TextMarginLeft = 0;
            this.btnManageProduct.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnManageProduct.UseDefaultRadiusAndThickness = true;
            this.btnManageProduct.Click += new System.EventHandler(this.btnManageProduct_Click);
            // 
            // btnLogOut
            // 
            this.btnLogOut.AllowAnimations = true;
            this.btnLogOut.AllowMouseEffects = true;
            this.btnLogOut.AllowToggling = false;
            this.btnLogOut.AnimationSpeed = 200;
            this.btnLogOut.AutoGenerateColors = false;
            this.btnLogOut.AutoRoundBorders = false;
            this.btnLogOut.AutoSizeLeftIcon = true;
            this.btnLogOut.AutoSizeRightIcon = true;
            this.btnLogOut.BackColor = System.Drawing.Color.Transparent;
            this.btnLogOut.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnLogOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogOut.BackgroundImage")));
            this.btnLogOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.ButtonText = "Đăng xuất";
            this.btnLogOut.ButtonTextMarginLeft = 0;
            this.btnLogOut.ColorContrastOnClick = 45;
            this.btnLogOut.ColorContrastOnHover = 45;
            this.btnLogOut.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnLogOut.CustomizableEdges = borderEdges6;
            this.btnLogOut.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogOut.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogOut.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogOut.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLogOut.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnLogOut.ForeColor = System.Drawing.Color.White;
            this.btnLogOut.IconLeft = null;
            this.btnLogOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogOut.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLogOut.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLogOut.IconMarginLeft = 11;
            this.btnLogOut.IconPadding = 10;
            this.btnLogOut.IconRight = null;
            this.btnLogOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogOut.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnLogOut.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogOut.IconSize = 25;
            this.btnLogOut.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.IdleBorderRadius = 3;
            this.btnLogOut.IdleBorderThickness = 1;
            this.btnLogOut.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.IdleIconLeftImage = null;
            this.btnLogOut.IdleIconRightImage = null;
            this.btnLogOut.IndicateFocus = false;
            this.btnLogOut.Location = new System.Drawing.Point(0, 410);
            this.btnLogOut.Margin = new System.Windows.Forms.Padding(0);
            this.btnLogOut.Name = "btnLogOut";
            this.btnLogOut.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogOut.OnDisabledState.BorderRadius = 3;
            this.btnLogOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.OnDisabledState.BorderThickness = 1;
            this.btnLogOut.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogOut.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogOut.OnDisabledState.IconLeftImage = null;
            this.btnLogOut.OnDisabledState.IconRightImage = null;
            this.btnLogOut.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnLogOut.onHoverState.BorderRadius = 3;
            this.btnLogOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.onHoverState.BorderThickness = 1;
            this.btnLogOut.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnLogOut.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLogOut.onHoverState.IconLeftImage = null;
            this.btnLogOut.onHoverState.IconRightImage = null;
            this.btnLogOut.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.OnIdleState.BorderRadius = 3;
            this.btnLogOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.OnIdleState.BorderThickness = 1;
            this.btnLogOut.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLogOut.OnIdleState.IconLeftImage = null;
            this.btnLogOut.OnIdleState.IconRightImage = null;
            this.btnLogOut.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.OnPressedState.BorderRadius = 3;
            this.btnLogOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.OnPressedState.BorderThickness = 1;
            this.btnLogOut.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnLogOut.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogOut.OnPressedState.IconLeftImage = null;
            this.btnLogOut.OnPressedState.IconRightImage = null;
            this.btnLogOut.Size = new System.Drawing.Size(200, 40);
            this.btnLogOut.TabIndex = 9;
            this.btnLogOut.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogOut.TextMarginLeft = 0;
            this.btnLogOut.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.btnLogOut.UseDefaultRadiusAndThickness = true;
            this.btnLogOut.Click += new System.EventHandler(this.btnLogOut_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(24, 7);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(156, 70);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 10;
            this.pictureBox1.TabStop = false;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.BlueViolet;
            this.panel1.Controls.Add(this.flowLayoutPanel1);
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Controls.Add(this.btnLogOut);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(200, 450);
            this.panel1.TabIndex = 11;
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(870, 450);
            this.Controls.Add(this.panel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "frmMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Shoppa";
            this.flowLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProductView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCartView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUserInfoView;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnManageProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogOut;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Panel panel1;
    }
}

