namespace Shoppa
{
    partial class frmTemp
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmTemp));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.flowLayoutPanel3 = new System.Windows.Forms.FlowLayoutPanel();
            this.label8 = new System.Windows.Forms.Label();
            this.txtSearchBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnSearch = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.flowLayoutPanel2 = new System.Windows.Forms.FlowLayoutPanel();
            this.label9 = new System.Windows.Forms.Label();
            this.cboCategoryFilter = new System.Windows.Forms.ComboBox();
            this.btnCategoryFilter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDeleteProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEditProduct = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.flowLayoutPanel3.SuspendLayout();
            this.flowLayoutPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // flowLayoutPanel3
            // 
            this.flowLayoutPanel3.AutoSize = true;
            this.flowLayoutPanel3.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.flowLayoutPanel3.Controls.Add(this.label8);
            this.flowLayoutPanel3.Controls.Add(this.txtSearchBox);
            this.flowLayoutPanel3.Controls.Add(this.btnSearch);
            this.flowLayoutPanel3.Location = new System.Drawing.Point(28, 27);
            this.flowLayoutPanel3.Name = "flowLayoutPanel3";
            this.flowLayoutPanel3.Size = new System.Drawing.Size(491, 35);
            this.flowLayoutPanel3.TabIndex = 55;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(5, 9);
            this.label8.Margin = new System.Windows.Forms.Padding(5, 9, 10, 5);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(66, 17);
            this.label8.TabIndex = 34;
            this.label8.Text = "Tìm kiếm:";
            // 
            // txtSearchBox
            // 
            this.txtSearchBox.AcceptsReturn = false;
            this.txtSearchBox.AcceptsTab = false;
            this.txtSearchBox.AnimationSpeed = 200;
            this.txtSearchBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearchBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearchBox.AutoSizeHeight = true;
            this.txtSearchBox.BackColor = System.Drawing.Color.Transparent;
            this.txtSearchBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearchBox.BackgroundImage")));
            this.txtSearchBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSearchBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtSearchBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSearchBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSearchBox.BorderRadius = 1;
            this.txtSearchBox.BorderThickness = 1;
            this.txtSearchBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSearchBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearchBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchBox.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtSearchBox.DefaultText = "";
            this.txtSearchBox.FillColor = System.Drawing.Color.White;
            this.txtSearchBox.HideSelection = true;
            this.txtSearchBox.IconLeft = null;
            this.txtSearchBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchBox.IconPadding = 10;
            this.txtSearchBox.IconRight = null;
            this.txtSearchBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchBox.Lines = new string[0];
            this.txtSearchBox.Location = new System.Drawing.Point(84, 3);
            this.txtSearchBox.MaxLength = 50;
            this.txtSearchBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearchBox.Modified = false;
            this.txtSearchBox.Multiline = true;
            this.txtSearchBox.Name = "txtSearchBox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearchBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchBox.OnIdleState = stateProperties4;
            this.txtSearchBox.Padding = new System.Windows.Forms.Padding(3);
            this.txtSearchBox.PasswordChar = '\0';
            this.txtSearchBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearchBox.PlaceholderText = "Nhập tên bạn muốn tìm kiếm";
            this.txtSearchBox.ReadOnly = false;
            this.txtSearchBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearchBox.SelectedText = "";
            this.txtSearchBox.SelectionLength = 0;
            this.txtSearchBox.SelectionStart = 0;
            this.txtSearchBox.ShortcutsEnabled = true;
            this.txtSearchBox.Size = new System.Drawing.Size(305, 29);
            this.txtSearchBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearchBox.TabIndex = 38;
            this.txtSearchBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.txtSearchBox.TextMarginBottom = 0;
            this.txtSearchBox.TextMarginLeft = 5;
            this.txtSearchBox.TextMarginTop = 0;
            this.txtSearchBox.TextPlaceholder = "Nhập tên bạn muốn tìm kiếm";
            this.txtSearchBox.UseSystemPasswordChar = false;
            this.txtSearchBox.WordWrap = true;
            // 
            // btnSearch
            // 
            this.btnSearch.AllowAnimations = true;
            this.btnSearch.AllowMouseEffects = true;
            this.btnSearch.AllowToggling = false;
            this.btnSearch.AnimationSpeed = 200;
            this.btnSearch.AutoGenerateColors = false;
            this.btnSearch.AutoRoundBorders = false;
            this.btnSearch.AutoSizeLeftIcon = true;
            this.btnSearch.AutoSizeRightIcon = true;
            this.btnSearch.BackColor = System.Drawing.Color.Transparent;
            this.btnSearch.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSearch.BackgroundImage")));
            this.btnSearch.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.ButtonText = "Tìm";
            this.btnSearch.ButtonTextMarginLeft = 0;
            this.btnSearch.ColorContrastOnClick = 45;
            this.btnSearch.ColorContrastOnHover = 45;
            this.btnSearch.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSearch.CustomizableEdges = borderEdges1;
            this.btnSearch.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSearch.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSearch.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSearch.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSearch.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSearch.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnSearch.ForeColor = System.Drawing.Color.White;
            this.btnSearch.IconLeft = null;
            this.btnSearch.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSearch.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSearch.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSearch.IconMarginLeft = 11;
            this.btnSearch.IconPadding = 10;
            this.btnSearch.IconRight = null;
            this.btnSearch.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSearch.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSearch.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSearch.IconSize = 25;
            this.btnSearch.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.IdleBorderRadius = 3;
            this.btnSearch.IdleBorderThickness = 1;
            this.btnSearch.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.IdleIconLeftImage = null;
            this.btnSearch.IdleIconRightImage = null;
            this.btnSearch.IndicateFocus = false;
            this.btnSearch.Location = new System.Drawing.Point(402, 5);
            this.btnSearch.Margin = new System.Windows.Forms.Padding(10, 5, 3, 3);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSearch.OnDisabledState.BorderRadius = 3;
            this.btnSearch.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnDisabledState.BorderThickness = 1;
            this.btnSearch.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSearch.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSearch.OnDisabledState.IconLeftImage = null;
            this.btnSearch.OnDisabledState.IconRightImage = null;
            this.btnSearch.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnSearch.onHoverState.BorderRadius = 3;
            this.btnSearch.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.onHoverState.BorderThickness = 1;
            this.btnSearch.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnSearch.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.onHoverState.IconLeftImage = null;
            this.btnSearch.onHoverState.IconRightImage = null;
            this.btnSearch.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.OnIdleState.BorderRadius = 3;
            this.btnSearch.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnIdleState.BorderThickness = 1;
            this.btnSearch.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.OnIdleState.IconLeftImage = null;
            this.btnSearch.OnIdleState.IconRightImage = null;
            this.btnSearch.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.OnPressedState.BorderRadius = 3;
            this.btnSearch.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSearch.OnPressedState.BorderThickness = 1;
            this.btnSearch.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnSearch.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSearch.OnPressedState.IconLeftImage = null;
            this.btnSearch.OnPressedState.IconRightImage = null;
            this.btnSearch.Size = new System.Drawing.Size(86, 26);
            this.btnSearch.TabIndex = 37;
            this.btnSearch.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSearch.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSearch.TextMarginLeft = 0;
            this.btnSearch.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSearch.UseDefaultRadiusAndThickness = true;
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Hủy bỏ";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges2;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.IconLeft = null;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRight = null;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.IdleBorderRadius = 3;
            this.btnCancel.IdleBorderThickness = 1;
            this.btnCancel.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(652, 426);
            this.btnCancel.Margin = new System.Windows.Forms.Padding(0);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 3;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnCancel.onHoverState.BorderRadius = 3;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnIdleState.BorderRadius = 3;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnPressedState.BorderRadius = 3;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(110, 28);
            this.btnCancel.TabIndex = 53;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            // 
            // btnClose
            // 
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowMouseEffects = true;
            this.btnClose.AllowToggling = false;
            this.btnClose.AnimationSpeed = 200;
            this.btnClose.AutoGenerateColors = false;
            this.btnClose.AutoRoundBorders = false;
            this.btnClose.AutoSizeLeftIcon = true;
            this.btnClose.AutoSizeRightIcon = true;
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClose.BackgroundImage")));
            this.btnClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.ButtonText = "Thoát";
            this.btnClose.ButtonTextMarginLeft = 0;
            this.btnClose.ColorContrastOnClick = 45;
            this.btnClose.ColorContrastOnHover = 45;
            this.btnClose.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnClose.CustomizableEdges = borderEdges3;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnClose.ForeColor = System.Drawing.Color.White;
            this.btnClose.IconLeft = null;
            this.btnClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClose.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClose.IconMarginLeft = 11;
            this.btnClose.IconPadding = 10;
            this.btnClose.IconRight = null;
            this.btnClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClose.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClose.IconSize = 25;
            this.btnClose.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnClose.IdleBorderRadius = 3;
            this.btnClose.IdleBorderThickness = 1;
            this.btnClose.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnClose.IdleIconLeftImage = null;
            this.btnClose.IdleIconRightImage = null;
            this.btnClose.IndicateFocus = false;
            this.btnClose.Location = new System.Drawing.Point(785, 426);
            this.btnClose.Margin = new System.Windows.Forms.Padding(0);
            this.btnClose.Name = "btnClose";
            this.btnClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClose.OnDisabledState.BorderRadius = 3;
            this.btnClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnDisabledState.BorderThickness = 1;
            this.btnClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClose.OnDisabledState.IconLeftImage = null;
            this.btnClose.OnDisabledState.IconRightImage = null;
            this.btnClose.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnClose.onHoverState.BorderRadius = 3;
            this.btnClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.onHoverState.BorderThickness = 1;
            this.btnClose.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnClose.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClose.onHoverState.IconLeftImage = null;
            this.btnClose.onHoverState.IconRightImage = null;
            this.btnClose.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnIdleState.BorderRadius = 3;
            this.btnClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnIdleState.BorderThickness = 1;
            this.btnClose.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnIdleState.IconLeftImage = null;
            this.btnClose.OnIdleState.IconRightImage = null;
            this.btnClose.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnPressedState.BorderRadius = 3;
            this.btnClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClose.OnPressedState.BorderThickness = 1;
            this.btnClose.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClose.OnPressedState.IconLeftImage = null;
            this.btnClose.OnPressedState.IconRightImage = null;
            this.btnClose.Size = new System.Drawing.Size(110, 28);
            this.btnClose.TabIndex = 51;
            this.btnClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClose.TextMarginLeft = 0;
            this.btnClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClose.UseDefaultRadiusAndThickness = true;
            // 
            // flowLayoutPanel2
            // 
            this.flowLayoutPanel2.AutoSize = true;
            this.flowLayoutPanel2.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.flowLayoutPanel2.Controls.Add(this.label9);
            this.flowLayoutPanel2.Controls.Add(this.cboCategoryFilter);
            this.flowLayoutPanel2.Controls.Add(this.btnCategoryFilter);
            this.flowLayoutPanel2.Location = new System.Drawing.Point(535, 28);
            this.flowLayoutPanel2.Name = "flowLayoutPanel2";
            this.flowLayoutPanel2.Size = new System.Drawing.Size(363, 33);
            this.flowLayoutPanel2.TabIndex = 54;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(5, 9);
            this.label9.Margin = new System.Windows.Forms.Padding(5, 9, 10, 5);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(98, 17);
            this.label9.TabIndex = 35;
            this.label9.Text = "Loại mặt hàng:";
            // 
            // cboCategoryFilter
            // 
            this.cboCategoryFilter.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategoryFilter.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cboCategoryFilter.FormattingEnabled = true;
            this.cboCategoryFilter.Location = new System.Drawing.Point(116, 5);
            this.cboCategoryFilter.Margin = new System.Windows.Forms.Padding(3, 5, 3, 3);
            this.cboCategoryFilter.Name = "cboCategoryFilter";
            this.cboCategoryFilter.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.cboCategoryFilter.Size = new System.Drawing.Size(145, 25);
            this.cboCategoryFilter.TabIndex = 39;
            // 
            // btnCategoryFilter
            // 
            this.btnCategoryFilter.AllowAnimations = true;
            this.btnCategoryFilter.AllowMouseEffects = true;
            this.btnCategoryFilter.AllowToggling = false;
            this.btnCategoryFilter.AnimationSpeed = 200;
            this.btnCategoryFilter.AutoGenerateColors = false;
            this.btnCategoryFilter.AutoRoundBorders = false;
            this.btnCategoryFilter.AutoSizeLeftIcon = true;
            this.btnCategoryFilter.AutoSizeRightIcon = true;
            this.btnCategoryFilter.BackColor = System.Drawing.Color.Transparent;
            this.btnCategoryFilter.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnCategoryFilter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCategoryFilter.BackgroundImage")));
            this.btnCategoryFilter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategoryFilter.ButtonText = "Lọc";
            this.btnCategoryFilter.ButtonTextMarginLeft = 0;
            this.btnCategoryFilter.ColorContrastOnClick = 45;
            this.btnCategoryFilter.ColorContrastOnHover = 45;
            this.btnCategoryFilter.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnCategoryFilter.CustomizableEdges = borderEdges4;
            this.btnCategoryFilter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCategoryFilter.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategoryFilter.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCategoryFilter.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCategoryFilter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCategoryFilter.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnCategoryFilter.ForeColor = System.Drawing.Color.White;
            this.btnCategoryFilter.IconLeft = null;
            this.btnCategoryFilter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCategoryFilter.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCategoryFilter.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCategoryFilter.IconMarginLeft = 11;
            this.btnCategoryFilter.IconPadding = 10;
            this.btnCategoryFilter.IconRight = null;
            this.btnCategoryFilter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCategoryFilter.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCategoryFilter.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnCategoryFilter.IconSize = 25;
            this.btnCategoryFilter.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnCategoryFilter.IdleBorderRadius = 3;
            this.btnCategoryFilter.IdleBorderThickness = 1;
            this.btnCategoryFilter.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnCategoryFilter.IdleIconLeftImage = null;
            this.btnCategoryFilter.IdleIconRightImage = null;
            this.btnCategoryFilter.IndicateFocus = false;
            this.btnCategoryFilter.Location = new System.Drawing.Point(274, 5);
            this.btnCategoryFilter.Margin = new System.Windows.Forms.Padding(10, 5, 3, 3);
            this.btnCategoryFilter.Name = "btnCategoryFilter";
            this.btnCategoryFilter.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategoryFilter.OnDisabledState.BorderRadius = 3;
            this.btnCategoryFilter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategoryFilter.OnDisabledState.BorderThickness = 1;
            this.btnCategoryFilter.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCategoryFilter.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCategoryFilter.OnDisabledState.IconLeftImage = null;
            this.btnCategoryFilter.OnDisabledState.IconRightImage = null;
            this.btnCategoryFilter.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnCategoryFilter.onHoverState.BorderRadius = 3;
            this.btnCategoryFilter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategoryFilter.onHoverState.BorderThickness = 1;
            this.btnCategoryFilter.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnCategoryFilter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCategoryFilter.onHoverState.IconLeftImage = null;
            this.btnCategoryFilter.onHoverState.IconRightImage = null;
            this.btnCategoryFilter.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCategoryFilter.OnIdleState.BorderRadius = 3;
            this.btnCategoryFilter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategoryFilter.OnIdleState.BorderThickness = 1;
            this.btnCategoryFilter.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCategoryFilter.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCategoryFilter.OnIdleState.IconLeftImage = null;
            this.btnCategoryFilter.OnIdleState.IconRightImage = null;
            this.btnCategoryFilter.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnCategoryFilter.OnPressedState.BorderRadius = 3;
            this.btnCategoryFilter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategoryFilter.OnPressedState.BorderThickness = 1;
            this.btnCategoryFilter.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnCategoryFilter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCategoryFilter.OnPressedState.IconLeftImage = null;
            this.btnCategoryFilter.OnPressedState.IconRightImage = null;
            this.btnCategoryFilter.Size = new System.Drawing.Size(86, 25);
            this.btnCategoryFilter.TabIndex = 36;
            this.btnCategoryFilter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCategoryFilter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCategoryFilter.TextMarginLeft = 0;
            this.btnCategoryFilter.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCategoryFilter.UseDefaultRadiusAndThickness = true;
            // 
            // btnDeleteProduct
            // 
            this.btnDeleteProduct.AllowAnimations = true;
            this.btnDeleteProduct.AllowMouseEffects = true;
            this.btnDeleteProduct.AllowToggling = false;
            this.btnDeleteProduct.AnimationSpeed = 200;
            this.btnDeleteProduct.AutoGenerateColors = false;
            this.btnDeleteProduct.AutoRoundBorders = false;
            this.btnDeleteProduct.AutoSizeLeftIcon = true;
            this.btnDeleteProduct.AutoSizeRightIcon = true;
            this.btnDeleteProduct.BackColor = System.Drawing.Color.Transparent;
            this.btnDeleteProduct.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDeleteProduct.BackgroundImage")));
            this.btnDeleteProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.ButtonText = "Xóa";
            this.btnDeleteProduct.ButtonTextMarginLeft = 0;
            this.btnDeleteProduct.ColorContrastOnClick = 45;
            this.btnDeleteProduct.ColorContrastOnHover = 45;
            this.btnDeleteProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnDeleteProduct.CustomizableEdges = borderEdges5;
            this.btnDeleteProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDeleteProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeleteProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeleteProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeleteProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDeleteProduct.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnDeleteProduct.ForeColor = System.Drawing.Color.White;
            this.btnDeleteProduct.IconLeft = null;
            this.btnDeleteProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDeleteProduct.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDeleteProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDeleteProduct.IconMarginLeft = 11;
            this.btnDeleteProduct.IconPadding = 10;
            this.btnDeleteProduct.IconRight = null;
            this.btnDeleteProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDeleteProduct.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDeleteProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDeleteProduct.IconSize = 25;
            this.btnDeleteProduct.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.IdleBorderRadius = 3;
            this.btnDeleteProduct.IdleBorderThickness = 1;
            this.btnDeleteProduct.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.IdleIconLeftImage = null;
            this.btnDeleteProduct.IdleIconRightImage = null;
            this.btnDeleteProduct.IndicateFocus = false;
            this.btnDeleteProduct.Location = new System.Drawing.Point(528, 426);
            this.btnDeleteProduct.Margin = new System.Windows.Forms.Padding(0);
            this.btnDeleteProduct.Name = "btnDeleteProduct";
            this.btnDeleteProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDeleteProduct.OnDisabledState.BorderRadius = 3;
            this.btnDeleteProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.OnDisabledState.BorderThickness = 1;
            this.btnDeleteProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDeleteProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDeleteProduct.OnDisabledState.IconLeftImage = null;
            this.btnDeleteProduct.OnDisabledState.IconRightImage = null;
            this.btnDeleteProduct.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnDeleteProduct.onHoverState.BorderRadius = 3;
            this.btnDeleteProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.onHoverState.BorderThickness = 1;
            this.btnDeleteProduct.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnDeleteProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteProduct.onHoverState.IconLeftImage = null;
            this.btnDeleteProduct.onHoverState.IconRightImage = null;
            this.btnDeleteProduct.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.OnIdleState.BorderRadius = 3;
            this.btnDeleteProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.OnIdleState.BorderThickness = 1;
            this.btnDeleteProduct.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteProduct.OnIdleState.IconLeftImage = null;
            this.btnDeleteProduct.OnIdleState.IconRightImage = null;
            this.btnDeleteProduct.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.OnPressedState.BorderRadius = 3;
            this.btnDeleteProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDeleteProduct.OnPressedState.BorderThickness = 1;
            this.btnDeleteProduct.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnDeleteProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDeleteProduct.OnPressedState.IconLeftImage = null;
            this.btnDeleteProduct.OnPressedState.IconRightImage = null;
            this.btnDeleteProduct.Size = new System.Drawing.Size(110, 28);
            this.btnDeleteProduct.TabIndex = 48;
            this.btnDeleteProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDeleteProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDeleteProduct.TextMarginLeft = 0;
            this.btnDeleteProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDeleteProduct.UseDefaultRadiusAndThickness = true;
            // 
            // btnEditProduct
            // 
            this.btnEditProduct.AllowAnimations = true;
            this.btnEditProduct.AllowMouseEffects = true;
            this.btnEditProduct.AllowToggling = false;
            this.btnEditProduct.AnimationSpeed = 200;
            this.btnEditProduct.AutoGenerateColors = false;
            this.btnEditProduct.AutoRoundBorders = false;
            this.btnEditProduct.AutoSizeLeftIcon = true;
            this.btnEditProduct.AutoSizeRightIcon = true;
            this.btnEditProduct.BackColor = System.Drawing.Color.Transparent;
            this.btnEditProduct.BackColor1 = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditProduct.BackgroundImage")));
            this.btnEditProduct.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.ButtonText = "Sửa";
            this.btnEditProduct.ButtonTextMarginLeft = 0;
            this.btnEditProduct.ColorContrastOnClick = 45;
            this.btnEditProduct.ColorContrastOnHover = 45;
            this.btnEditProduct.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnEditProduct.CustomizableEdges = borderEdges6;
            this.btnEditProduct.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditProduct.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditProduct.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditProduct.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditProduct.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEditProduct.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnEditProduct.ForeColor = System.Drawing.Color.White;
            this.btnEditProduct.IconLeft = null;
            this.btnEditProduct.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditProduct.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnEditProduct.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEditProduct.IconMarginLeft = 11;
            this.btnEditProduct.IconPadding = 10;
            this.btnEditProduct.IconRight = null;
            this.btnEditProduct.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditProduct.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnEditProduct.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEditProduct.IconSize = 25;
            this.btnEditProduct.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.IdleBorderRadius = 3;
            this.btnEditProduct.IdleBorderThickness = 1;
            this.btnEditProduct.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.IdleIconLeftImage = null;
            this.btnEditProduct.IdleIconRightImage = null;
            this.btnEditProduct.IndicateFocus = false;
            this.btnEditProduct.Location = new System.Drawing.Point(408, 426);
            this.btnEditProduct.Margin = new System.Windows.Forms.Padding(0);
            this.btnEditProduct.Name = "btnEditProduct";
            this.btnEditProduct.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditProduct.OnDisabledState.BorderRadius = 3;
            this.btnEditProduct.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.OnDisabledState.BorderThickness = 1;
            this.btnEditProduct.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditProduct.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditProduct.OnDisabledState.IconLeftImage = null;
            this.btnEditProduct.OnDisabledState.IconRightImage = null;
            this.btnEditProduct.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.btnEditProduct.onHoverState.BorderRadius = 3;
            this.btnEditProduct.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.onHoverState.BorderThickness = 1;
            this.btnEditProduct.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.btnEditProduct.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEditProduct.onHoverState.IconLeftImage = null;
            this.btnEditProduct.onHoverState.IconRightImage = null;
            this.btnEditProduct.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.OnIdleState.BorderRadius = 3;
            this.btnEditProduct.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.OnIdleState.BorderThickness = 1;
            this.btnEditProduct.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEditProduct.OnIdleState.IconLeftImage = null;
            this.btnEditProduct.OnIdleState.IconRightImage = null;
            this.btnEditProduct.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.OnPressedState.BorderRadius = 3;
            this.btnEditProduct.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProduct.OnPressedState.BorderThickness = 1;
            this.btnEditProduct.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.btnEditProduct.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEditProduct.OnPressedState.IconLeftImage = null;
            this.btnEditProduct.OnPressedState.IconRightImage = null;
            this.btnEditProduct.Size = new System.Drawing.Size(110, 28);
            this.btnEditProduct.TabIndex = 50;
            this.btnEditProduct.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditProduct.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditProduct.TextMarginLeft = 0;
            this.btnEditProduct.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEditProduct.UseDefaultRadiusAndThickness = true;
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.ColumnHeader;
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Location = new System.Drawing.Point(28, 74);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.Size = new System.Drawing.Size(869, 325);
            this.dataGridView1.TabIndex = 42;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.BlueViolet;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Thống kê";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges7;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton1.IdleBorderRadius = 3;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(270, 426);
            this.bunifuButton1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 3;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.DarkOrchid;
            this.bunifuButton1.onHoverState.BorderRadius = 3;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.DarkOrchid;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton1.OnIdleState.BorderRadius = 3;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton1.OnPressedState.BorderRadius = 3;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.BlueViolet;
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(110, 28);
            this.bunifuButton1.TabIndex = 56;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // frmTemp
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(934, 487);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.flowLayoutPanel3);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.flowLayoutPanel2);
            this.Controls.Add(this.btnDeleteProduct);
            this.Controls.Add(this.btnEditProduct);
            this.Controls.Add(this.dataGridView1);
            this.Name = "frmTemp";
            this.Text = " ";
            this.flowLayoutPanel3.ResumeLayout(false);
            this.flowLayoutPanel3.PerformLayout();
            this.flowLayoutPanel2.ResumeLayout(false);
            this.flowLayoutPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel3;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearchBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSearch;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClose;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel2;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.ComboBox cboCategoryFilter;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCategoryFilter;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDeleteProduct;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEditProduct;
        private System.Windows.Forms.DataGridView dataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
    }
}